#!/bin/sh
# run load/save with dba only, without memory trace (debug=9).
# this should catch most of existing errors, and needs only one external file.
mkdir .testbox .dumphtml
chmod -R a+rw .testbox .dumphtml
php -Cq -d register_argc_argv=1 test.php test=SetupWiki test=DumpHtml db=dba level=10 debug=1
