<?php

$tracker = 'unknown';

switch (TRACKER_TYPE) {
	case 'mantis':
		$tracker = 'Mantis';
		break;
	case 'fusionforge':
		$tracker = 'FusionForge';
		break;
	case 'demo':
		$tracker = 'Demo Server';
		break;
	default:
		$tracker = 'Unknown';
		break;
}
?>
<body>
<h1><?php echo 'Thanks for using this '.$tracker.' OSLC-CM V1 compatible REST server' ?></h1>

<p>To test, please access one of the following links, using the proper "Accept:" content type header :</p>
<ul>
	<li>
	<p><tt>curl -H "Accept: application/x-oslc-disc-service-provider-catalog+xml" -X GET <a 
		href="<?php 
				$req_array = _getRequestArray();
				echo util_make_url($this->baseUrl().'/cm/oslc-services/?type='.$req_array['type'].'&id='.$req_array['id'].'&pluginname='.$req_array['pluginname']);
			?>
		">
		.../cm/oslc-services/</a></tt> : to retrieve an RDF/XML OSLC Service Provider Catalog document.</p>
	</li>
</ul>
</body>
