include ../../GNUmakefile.defaults

all:
	@echo "No default action"

install:
	install -d -m 755 $(DESTDIR)$(pkgdatadir)/plugins/scmhg/cgi-bin/
	install -d -m 755 $(DESTDIR)$(pkgdatadir)/plugins/scmhg/www/cgi-bin/
