#! /bin/sh
# Add universe required by cowbuilder
#grep "main$" /etc/apt/sources.list | sed 's/main/universe/' >> /etc/apt/sources.list
#CB#grep jaunty /etc/apt/sources.list | sed 's/jaunty/jaunty-updates/' >> /etc/apt/sources.list
#CB#cat /etc/apt/sources.list
