#!/bin/sh
#---------------------------------------------------------------------------
# Novaforge is a registered trade mark from Bull S.A.S
# Copyright (C) 2007 Bull S.A.S.
# 
# http://novaforge.org/
#
#
# This file has been developped within the Novaforge(TM) project from Bull S.A.S
# and contributed back to GForge community.
#
# GForge is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# GForge is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this file; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#---------------------------------------------------------------------------


# Source functions
if [ -e %DATADIR%/%NAME%/config/util/functions ] ; then
	. %DATADIR%/%NAME%/config/util/functions
else
	exit 0
fi
init_variables $*
source_init_parameters
#
# Save plugin config
#
save_plugin_config %PLUGIN_NAME%
#
# Unregister plugin
#
unregister_plugin %PLUGIN_NAME%
#
# Blank %SYSCONFDIR%/httpd/conf.d/%NAME%-plugin-%PLUGIN_NAME%.conf
#
if [ $SILENT -eq 0 ] ; then
	echo -e "$PREFIX_CHAR Blanking file '%SYSCONFDIR%/httpd/conf.d/%NAME%-plugin-%PLUGIN_NAME%.conf'"
fi
rm -f %SYSCONFDIR%/httpd/conf.d/%NAME%-plugin-%PLUGIN_NAME%.conf
touch %SYSCONFDIR%/httpd/conf.d/%NAME%-plugin-%PLUGIN_NAME%.conf
chown root.root %SYSCONFDIR%/httpd/conf.d/%NAME%-plugin-%PLUGIN_NAME%.conf
chmod 600 %SYSCONFDIR%/httpd/conf.d/%NAME%-plugin-%PLUGIN_NAME%.conf
#
# Ignore previous errors
#
exit 0
