<?php
/**
  *
  * SourceForge Terms of Service text
  *
  * This should be pure HTML content, as it is included in several
  * other pages.
  *
  * SourceForge: Breaking Down the Barriers to Open Source Development
  * Copyright 1999-2001 (c) VA Linux Systems
  * http://sourceforge.net
  *
  * @version   $Id: tos_text.php,v 1.3 2001/05/22 15:47:25 pfalcon Exp $
  *
  */
?>

<p>
<h2>SourceForge Terms of Service Agreement</h2>
</p>

<p>
<B>0. PRELIMINARY</B>
</p>

<p>
This site runs a Debianised version of the Sourceforge code.  This
code has been made public by the Sourceforge crew at VA Linux (and/or
other companies) under the terms of the GNU GPL.  As such, the code in
itself comes with no warranty whatsoever, as does the Debian
packaging.  Therefore, the people who authored the code and the people
who made a Debian package of it shall not hold any liability for
whatever problems you do, or do not, encounter by using, or by not
using this site.

<p>
The following terms are only binding to the local Sourceforge site
administrator and you, the user of this site.

<p>
<B>1. ACCEPTANCE OF TERMS</B> 
</p>

<p>
A person's use of this Sourceforge site and any of its Services is
subject to the site's then-current Terms of Service ("TOS"), which are
defined by the local Sourceforge administrator and/or some other
entity.  The local Sourceforge administrator publishes these TOS here.
He might change them at his will, and is supposed to update this page
and take reasonable action towards informing the users.
</p>

<p>
If you are seeing this sentence, the local Sourceforge administrator
has probably not changed these terms according to the local policy.
Please contact him and remind him to do so.
</p>

<p>
<B>2. DESCRIPTION OF SERVICE</B> 
</p>

<p>
SourceForge is a website owned and operated by VA Linux Systems, Inc., for
the purpose of fostering software development and content creation under
Open-Source Initiative ("OSI")-approved licenses or other arrangements
relating to software and/or content development that may be approved by
SourceForge (the "Purpose").  SourceForge currently offers users access to a
rich collection of on-line resources for Open Source  software  development
and content creation, including various  communications tools, source code
control and project management tools, online forums, shopping services,
personalized content and branded programming through its network of
properties (collectively, the "Services").
</p>

<p>
This Sourceforge site provides (or should provide) the same services.
Local policy or action might have changed it though, refer to the
local Sourceforge administrator to know more.

<p>
<B>3. REGISTRATION OBLIGATIONS</B> 
</p>

<p>
If required by the site in question, each user should: (a) provide
true, accurate, current and complete information on the Service's
registration form (collectively, the "Registration Data") and (b)
maintain and promptly update the Registration Data as necessary.
Whether this "should" is a "must", and what happens if the user
doesn't abide by this rule, is a matter of local policy.
</p>

<p>
Each user will receive a password and account designation upon
completing the Service's registration process and is wholly
responsible for maintaining the confidentiality thereof and wholly
liable for all activities occurring thereunder.  Again, local policy
might override this.
</p>

<p>
SourceForge handles user Registration Data in accordance with the
<a href="/tos/privacy.php">SourceForge Privacy Policy</a>.  This
policy should be accorded to the local policy.
</p>

<p>
<B>4. CONTENT</B> 
</p>

<p>
All information, data, text, software, music, sound, photographs,
graphics, video, messages or any other materials whatsoever
(collectively, "Content"), whether publicly posted or privately
transmitted, are the sole responsibility of the person from which such
Content originated.  The local Sourceforge site is probably not
responsible for the trouble that can arise from it.  In any case, this
should be specified by the local Sourceforge administrator.
</p>

<p>
Licensing and Other Terms Applying to Code and Other Content Posted on
SourceForge:
</p>

<p>
Use, reproduction, modification, and other intellectual property
rights to data stored in CVS or as a file release and posted by any
user on this site ("Source Code") shall be subject to the
(OSI-approved or not) license applicable to such Source Code.
</p>

<p>
With respect to text or data entered into and stored by publicly-accessible
site features such as message boards and bug trackers ("SourceForge Public
Content"), the submitting user retains ownership of such SourceForge Public
Content; with respect to publicly-available statistical content which is
generated by the site to monitor and display project activity, such content
is owned by this Sourceforge site.  If the local administator has
anything to add or change, he should explicit it here.
</p>

<p>
<B>5. NO RESALE OF SERVICE</B> 
</p>

<p>
You agree not to sell, resell or offer for any commercial purposes,
any portion of the Services, use of the Services or access to the
Services.  That is, unless the local Sourceforge administator grants
you the rights to do so.
</p>

<p>
<B>6. GENERAL PRACTICES REGARDING USE AND STORAGE</B> 
</p>

<p>
This Sourceforge site may establish general practices and limits
concerning use of the Services, as defined by posted Service-specific
Rules.  While this site will use reasonable efforts to back up site
data and make such data available in the event of loss or deletion,
the local administrator has no responsibility or liability for the
deletion or failure to store any messages and other communications or
other Content maintained or transmitted by any Service.
</p>

<p>
<B>7. TERMINATION</B>
</p>

<p>
A user's account may be terminated for reasons that include, but are
not limited to, the following: 1.) violation of these TOS; 2.) abuse
of site resources or attempt to gain unauthorized entry to the site or
site resources; 3.) use of Service in a manner inconsistent with the
Purpose; 4.)  a user's request for such termination; 5.)  requirement
of applicable law, regulation, court or governing agency order; and
6.) whatever the local site administrator feels appropiate.
</p>

<p>
<B>8. LINKS</B>
</p>

<p>
This Sourceforge site, any Service in it, or a third party may provide
links to other Websites.  This Sourceforge site exercises no control
whatsoever over such other Websites and Web-based resources and is not
responsible or liable for the availability thereof or the Content,
advertising, products or other materials thereon.  This site shall not
be responsible or liable, directly or indirectly, for any damage or
loss incurred or suffered by any user in connection therewith.
</p>

<p>
<B>9. INDEMNITY; DISCLAIMER OF WARRANTIES; LIMITATION OF LIABILITY</B> 
</p>

<p>
This section should be filled in by the local Sourceforge
administrator.  The following text is here just as an exemple of what
it says for the original SourceForge site at the time of writing.

<p>
EACH USER'S USE OF THE SERVICE IS AT HIS OR HER SOLE RISK. THE SERVICE
IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS AND SOURCEFORGE
ASSUMES NO RESPONSIBILITY FOR THE TIMELINESS, DELETION, MIS-DELIVERY
OR FAILURE TO STORE ANY USER COMMUNICATIONS OR PERSONALIZATION
SETTINGS.  [...] SOURCEFORGE EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY
KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO THE
IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
PURPOSE AND NON-INFRINGEMENT.

<p>
<b>10. TRADEMARK INFORMATION</b>
</p>

<p>
SourceForge, the SourceForge logo and other SourceForge trademarks,
service marks, and product and service names are trademarks of VA
Linux Systems Inc.  (the "SourceForge Marks").  VA Linux Systems is a
trademark of VA Linux Systems, Inc.  Linux is a registered trademark
of Linus Torvalds.  All other marks are property of their respective
owners.  Users may display or use the SourceForge Marks only in
accordance with VA's Trademark Use Guidelines.
</p>

<p>
<b>11. COPYRIGHTS</b>
</p>

<p>
SourceForge respects the intellectual property of all parties and they
ask their users to do the same.  Whether this site acts the same way
is entirely a matter of local policy.  Contact the local Sourceforge
administrator for more information.

<p>
<b>12. GENERAL INFORMATION</b>
</p>

<p>
The TOS constitute the entire agreement between each user and the
owners of this Sourceforge site.  Each user may be subject to
additional terms and conditions that may apply when that user uses
affiliate services, third party content or third party software.  This
clause being very vague, it is expected from the local administrator
that precisions are inserted here.
</p>

<p>
<b>13. VIOLATIONS</b>
</p>

<p>
Please report any violations of the TOS, any alleged copyright
infringements or any other matters to the local Sourceforge
administrator.
</p>
