#!/usr/bin/perl
#
#  Clean LDAP database 
#  by pfalcon@users.sourceforge.net 2000-10-18
#  $Id: ldap-clean,v 1.4 2000/12/10 23:45:19 pfalcon Exp $
#

require("include.pl");  # Include all the predefined functions
&parse_local_inc;

$cmd = "${ldap_prefix}ldapdelete -D '$sys_ldap_admin_dn' -W -r '$sys_ldap_base_dn'";
print "Destroying LDAP database...\n";
system($cmd);
