#!/usr/bin/perl
#
#  Clean LDAP database 
#  by pfalcon@users.sourceforge.net 2000-10-18
#  $Id: ldap-clean,v 1.5 2001/01/08 16:57:21 tperdue Exp $
#

require("include.pl");  # Include all the predefined functions
&parse_local_inc;

$cmd = "${ldap_prefix}ldapdelete -h $sys_ldap_host -p $sys_ldap_port -D '$sys_ldap_admin_dn' -W -r '$sys_ldap_base_dn'";
print "Destroying LDAP database...\n";
system($cmd);
