#!/bin/bash
# Tricks to install unavailable packages - used by install.sh and install-src.sh
#
# Copyright (C) 2011  Roland Mas
# Copyright (C) 2011  Olivier Berger - Institut Telecom
# Copyright (C) 2014  Inria (Sylvain Beucler)
#
# This file is part of FusionForge. FusionForge is free software;
# you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software
# Foundation; either version 2 of the Licence, or (at your option)
# any later version.
#
# FusionForge is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with FusionForge; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


function backports_deb {
    if grep -q ^7 /etc/debian_version; then
	# Install OpenSSH 6.6 to get AuthorizedKeysCommand support
	if [ ! -f /etc/apt/sources.list.d/backports.list ]; then
	    echo 'deb http://http.debian.net/debian wheezy-backports main' \
		> /etc/apt/sources.list.d/backports.list
	    apt-get update
	fi
	if dpkg-query -s openssh-server | grep -q 'Version: 1:6.0'; then
	    apt-get -y install openssh-server -t wheezy-backports
	fi

	# fusionforge-plugin-scmbzr depends on loggerhead (>=
	# 1.19~bzr477~), but wheezy only has 1.19~bzr461-1, so we need
	# to manually "Backport" a more recent dependency
	if ! dpkg-query -s loggerhead >/dev/null 2>&1 ; then
	    # install loggerhead with its dependencies
	    # we need gdebi to make sure dependencies are installed too (simple dpkg -i won't)
	    apt-get -y install gdebi-core wget
	    wget -c http://snapshot.debian.org/archive/debian/20121107T152130Z/pool/main/l/loggerhead/loggerhead_1.19%7Ebzr477-1_all.deb
	    gdebi --non-interactive loggerhead_1.19~bzr477-1_all.deb
	fi
    fi
}

function backport_rpm_from_fedora {
    rebuild_one_rpm --enablefedora $*
}

function rebuild_rpm_from_centos {
    rebuild_one_rpm --rebuild $*
}

function rebuild_one_rpm {
    enablefedsrc=
    enablefed=
    if [ "$1" = "--enablefedora" ] ; then
	enablefedsrc="--enablerepo=fedora-source --enablerepo=fedora-updates-source"
    	shift
    fi

    rebuild=no
    if [ "$1" = "--rebuild" ] ; then
    	rebuild=yes
    	shift
    fi

    src=
    if [ "$1" = "--source-package" ] ; then
    	src=$2
    	shift
    	shift
    fi

    target=$1
    shift
    others="$*"

    src=${src:-$target}

    rebuild_needed=no
    if [ $rebuild = yes ] ; then
	rebuild_needed=yes
    else
	for i in $target $others ; do
	    if ! yum list $i >/dev/null 2>&1; then
		rebuild_needed=yes
		break
	    fi
	done
    fi

    if [ $rebuild_needed = yes ] ; then
	yumdownloader $enablefedsrc --source $src

	if [ -n "$DEPS" ]; then
	    yum install -y $DEPS
	fi

	for i in $src-*.src.rpm ; do
	    if [ $rebuild = yes ] || [ ! -e "$i.done" ] ; then
		rpmbuild --rebuild $src-*.src.rpm
	    fi
	    mv -f "$i" "$i.done"
	done
	if [ -n "$REMOVEDEPS" ] ; then
	    : yum remove -y $REMOVEDEPS
	fi

	for i in $target $others ; do
	    yum remove -y $i
	done
	for i in $target $others ; do
	    yum install -y ~/rpmbuild/RPMS/*/$i-[0-9]*.*.rpm || rpm -i ~/rpmbuild/RPMS/*/$i-[0-9]*.*.rpm
	done
    else
	yum install -y $target $others
    fi
}

# TODO: compile in a different job and use mockbuild?
function backports_rpm {
    set -ex

    # Fedora/RHEL/CentOS version:
    os_version=$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))

    if ! rpm -q fedora-release >/dev/null; then
	# Enable EPEL
	yum install -y epel-release

	# Prepare manual backports
	cat <<'EOF' > /etc/yum.repos.d/fedora-source.repo
[fedora]
name=Fedora 22
failovermethod=priority
metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-22&arch=$basearch
enabled=0
gpgcheck=0
[fedora-updates]
name=Fedora 22 Updates
failovermethod=priority
metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-released-f22&arch=$basearch
enabled=0
gpgcheck=0
[fedora-source]
name=Fedora 22 - Source
failovermethod=priority
metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-source-22&arch=$basearch
enabled=0
gpgcheck=0
[fedora-updates-source]
name=Fedora 22 Updates - Source
failovermethod=priority
metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-released-source-f22&arch=$basearch
enabled=0
gpgcheck=0
EOF

	# Speed-up by recreating 'fastestmirror' now partial cache
	# (/var/cache/yum/x86_64/7/timedhost.txt)
        yum clean plugins

	yum install -y yum-utils  # yumdownloader
	if [ ! -e /usr/bin/rpmbuild ] ; then
	    yum install -y rpm-build
	fi
    fi

    case $os_version in
	7)
	    # viewvc: not available in EPEL7
	    if yum list viewvc >/dev/null 2>&1; then
		yum install -y viewvc
	    else
		DEPS="python-devel python-pygments"
		REMOVEDEPS="python-devel"
		yum install -y $DEPS
		yumdownloader --enablerepo=fedora-source --enablerepo=fedora-updates-source \
			      --source viewvc
		rpm -ivh viewvc-*.src.rpm
		# remove cvsgraph dependency, not available in EPEL7
		sed -i -e '/Requires:\s*cvsgraph/d' ~/rpmbuild/SPECS/viewvc.spec
		rpmbuild -bb ~/rpmbuild/SPECS/viewvc.spec
		yum install -y ~/rpmbuild/RPMS/*/viewvc-[0-9]*.rpm
	    fi

	    # mediawiki not available in EPEL
	    # Note: we don't support mediawiki > 1.19 as of 2015-06
	    # Note: no stable/backportable mediawiki rpm as of 2015-09 -> manual install + mock rpm?
	    if false; then
                if yum list mediawiki >/dev/null 2>&1; then
                    yum install -y mediawiki
                else
                    DEPS="httpd-filesystem"
                    yum install --enablerepo=fedora -y $DEPS
                    yumdownloader --enablerepo=fedora-source --enablerepo=fedora-updates-source \
                                  --source mediawiki
                    rpm -ivh mediawiki-*.src.rpm
		    # Work-arounds for mediawiki-1.25.1-3.fc22
                    # don't backport php-pecl-jsonc which has lots of deps, use built-in php-json
                    sed -i -e '/Requires/ s/, php-pecl-jsonc//' ~/rpmbuild/SPECS/mediawiki.spec
                    sed -i -e '/Requires: php-pecl-jsonc/d' ~/rpmbuild/SPECS/mediawiki.spec
                    # drop new-style php requires
                    sed -i -e '/Requires: php(/d' ~/rpmbuild/SPECS/mediawiki.spec
                    # drop test-suite
                    sed -i -e '/BuildRequires: /d' ~/rpmbuild/SPECS/mediawiki.spec
                    sed -i -e '/^%check/,/^php phpunit.php/d' ~/rpmbuild/SPECS/mediawiki.spec
                    rpmbuild -bb ~/rpmbuild/SPECS/mediawiki.spec
                    yum install -y ~/rpmbuild/RPMS/noarch/mediawiki-[0-9]*.rpm
                fi
	    fi

	    yum --enablerepo=epel -y install php-tidy
	    # php-htmlpurifier-htmlpurifier Requires, available in EPEL6 but not EPEL7
	    DEPS="php-pear"
	    REMOVEDEPS=$DEPS
	    backport_rpm_from_fedora php-channel-htmlpurifier
	    ;;
    esac

    # libnss-pgsql: no available package for RHEL; though it's available in Fedora
    # (there's also http://yum.postgresql.org/8.4/redhat/rhel-5-x86_64/)
    DEPS="xmlto gcc postgresql-devel"
    REMOVEDEPS=$DEPS
    backport_rpm_from_fedora libnss-pgsql

    DEPS="dos2unix"
    REMOVEDEPS=$DEPS
    backport_rpm_from_fedora php-nusoap

    DEPS=""
    REMOVEDEPS=$DEPS
    backport_rpm_from_fedora php-htmlpurifier-htmlpurifier

    mkdir -p /usr/src/fusionforge/build/RPMS/
    cp -r ~/rpmbuild/RPMS/* /usr/src/fusionforge/build/RPMS/

    # TODO: postfix: rebuild from RHEL/CentOS sources with pgsql enabled,
    # so we can test mta-postfix
}

function suse_check_release {
	supported=$(. /etc/os-release; echo $VERSION | grep "42\.[12]")
	if test -z "$supported"; then
		echo "unsupported openSUSE version"
		exit 1
	fi
}

function suse_install_repos {
	has_repo=$(zypper lr | grep 'Apache:Modules' | sed 's,  ,,g')
	if test -z "$has_repo"; then
		dist_path=$(. /etc/os-release; echo $PRETTY_NAME | sed 's, ,_,g')
		zypper ar http://download.opensuse.org/repositories/Apache:/Modules/$dist_path/ Apache:Modules
	fi
}

function suse_install_rpms {
	# Install build dependencies
	modules="$*"
	instmods=""
	for m in $modules; do
		if ! rpm -q $m >/dev/null; then
			instmods="$instmods $m"
		fi
	done
	if [ -n "$instmods" ] ; then
		zypper install -y $instmods
	fi
}
