<body>
<h1><?php echo 'Thanks for using this FusionForge OSLC Core V2 compatible REST server' ?></h1>

<p>To test, please access one of the following links, using the proper "Accept:" content type header :</p>
<ul>
	<li>
	<p><tt>curl -H "Accept: application/x-oslc-disc-service-provider-catalog+xml" -X GET <a 
		href="<?php 
				$catalog_uri = $this->serverUrl() . util_make_uri($this->baseUrl().'/cm/oslc-services/');
				echo $catalog_uri;
			?>
		"><?php
		echo $catalog_uri;
		?>
		</a></tt> : to retrieve an HTML view of an RDF/XML OSLC Service Provider Catalog document.</p>
	</li>
</ul>
</body>
