<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">
<?php 
	$project = $this->data['project'];
	$tracker = $this->data['tracker'];
?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>OSLC Creation UI</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<style type="text/css">
		
		body { 	font: 13px Myriad,Arial,Helvetica,clean,sans-serif; 	
				*font-size: small;	
				*font: x-small;}
				
		h1 {	font-size: 1.5em; 	
				font-weight: normal;	
				line-height: 1em; 	
				margin-top: 1em;	
				margin-bottom:0;}
				
		h2 { 	font-size: 1.1667em;
				font-weight: bold; 	
				line-height: 1.286em; 	
				margin-top: 1.929em; 	
				margin-bottom:0.643em;}
		
		h3, h4, h5, h6 {	font-size: 1em; 	
							font-weight: bold; 	
							line-height: 1.5em; 	
							margin-top: 1.5em; 	
							margin-bottom: 0;}
							
		p { 	font-size: 1em;
				margin-top: 1.5em;
				margin-bottom: 1.5em;
				line-height: 1.5em;}
		
		body {
			margin: 2em;
		}
		
		table td {
			padding: 2px;
		}
		
		</style>
		
        <script type="text/javascript" src="/scripts/jquery/jquery.js"></script>
        <script type="text/javascript" src="/plugins/oslc/scripts/json.js"></script>
		
		<script type="text/javascript">

jQuery(function(){

	var project = "<?php echo $project;?>";
	var tracker = "<?php echo $tracker;?>";
	var URL = '<?php echo $this->baseUrl(); ?>'+"/cm/project/"+project+"/tracker/"+tracker;
	var result;
	var postdata;
	var userpass;
	var error = false;

	jQuery("#createbutton").click(function() {
		createBugData();
		jQuery.ajax({
			type: "POST",
			url: URL,
			data: jQuery.toJSON(postdata),
			dataType: 'json',
			beforeSend: function(xhr) {
				xhr.setRequestHeader("Content-Type","application/x-oslc-cm-change-request+json");
			},
			success: function(data, ioArgs) {
				alert("The url of the bug just created is: "+data);                  	 	                        
				result = data;
				refresh();
			},
			error: function(jqXHR, textStatus, errorThrown) {
				//alert(textStatus+' x '+jqXHR.responseText);
               	var response = jQuery.parseJSON(jqXHR.responseText);
               	var errmsg, errcode;
               	for (var key in response) {
					var obj = response[key];						   
					if(key=="oslc_cm:Error") {
						for (var i in obj) {
							if(i=="oslc_cm:statusCode")	{
								errcode = obj[i];
							}else if(i=="oslc_cm:message") {
								errmsg = obj[i];
							}
						}
						var errtext = "Error " + errcode + ": " + errmsg;
						alert(errtext);
					}
				}
			}
		});
	});

	jQuery("#creatensendbutton").click(function() {
		createBugData();
		jQuery.ajax({
			type: "POST",
			url: URL,
			data: jQuery.toJSON(postdata),
			beforeSend: function(xhr) {
				xhr.setRequestHeader("Content-Type","application/x-oslc-cm-change-request+json");
			},
			dataType: "json",
			success: function(data, ioArgs) {
				alert("The url of the bug just created is: "+data);                  	 	                        
				result = data;
				postdata['rdf:resource'] = result;
				postdata['oslc_cm:label'] = postdata['dc:title'];
				postdataArr = [];
				postdataArr.push(postdata);
				var datatosend = {'oslc_cm:results': postdataArr};
				datatosend = datatosend.toSource();
				refresh();
				//alert(datatosend);
				respondWithPostMessage(datatosend);
			},
			error: function(jqXHR, textStatus, errorThrown) {
               	var response = jQuery.parseJSON(jqXHR.responseText);
               	var errmsg, errcode;
				for (var key in response) {
						var obj = response[key];						   
						if(key=="oslc_cm:Error")   {
							for (var i in obj) {
								if(i=="oslc_cm:statusCode")	{
									errcode = obj[i];
								} else if(i=="oslc_cm:message")	{
									errmsg = obj[i];
								}
							}
						}
						var errtext = "Error " + errcode + ": " + errmsg;
						alert(errtext);
				}
			}
		});
	});			

	var convertToByteArray = function(data) {
		var bin=[] ;
		for (var i=0; i<data.length; i++){
			bin.push(data.charCodeAt(i));
		}
		return bin;
	}

	var createBugData = function() {
		error = false;

		postdata = {};
		var temp = jQuery("#titletext").val();
		if(temp=="")	{
			alert("Bug Title cannot be empty!");
			error = true;
			return;
		}else	{
			postdata['dcterms:title'] = temp;
		}

		temp = jQuery("#descriptiontext").val();
		if(temp=="")	{
			alert("Bug description cannot be empty!");
			error = true;
			return;
		}else	{
			postdata['dcterms:description'] = temp;
		}

		temp = jQuery("#prioritylist").val();
		if(temp!="none selected")	{
			postdata['helios_bt:priority'] = temp;
		}
		//alert(postdata.toSource());
	}

	function respondWithPostMessage(/*string*/ response) {
		window.parent.postMessage("oslc-response:" + response, "*");
			//TODO if window is not parented window.postMessage to be used
			//which shud be ignored
	}

	function refresh() {
		jQuery(".textclass").each(function(item, index, array)	{
			item.value = "";
		});
		
		jQuery(".listclass").each(function(item, index, array)	{
			item.selectedIndex = 0;
		});	
	}
});

		</script>
    </head>
    <body>
        <h1><?php echo strtoupper($project); ?>: Creation UI for OSLC</h1><hr/>
        <!-- <p>some details of the query and blah blah to be added here</p> -->
        
        <br>
        <!-- <p><b>Project: <?php echo $project ?></b></p> -->
        <table>
        	     		
        </table>
        <table border=1>        
        <tr><td>
	        <table CELLSPACING=2 CELLPADDING=2 id="main">
        		<tr><td width=50% valign="top">
	        	<fieldset>
        		<legend><em>Title *</em></legend>
		        <table>
					<tr>
						<td><input class="textclass" id="titletext" size="40" type=text></td>
					</tr>
				</table>
				</fieldset>
				</td>
				<td width=50%>
	        	<fieldset>
        		<legend><em>Description *</em></legend>
		        <table>
					<tr>
						<td><textarea class="textclass" id="descriptiontext" cols="40" rows="3"></textarea></td>
					</tr>
				</table>
				</fieldset>
				</td></tr>
				<tr><td width=50%>
	        	<fieldset>
        		<legend><em>Priority</em></legend>
		        <table>
					<tr>
						<td><select class="listclass" id="prioritylist">
							<option value="none selected" selected="selected">Select</option>
        					<option value="1">1 - <?php echo _('Lowest') ?></option>
        					<option value="2">2</option>
        					<option value="3" selected="selected">3</option>
        					<option value="4">4</option>
        					<option value="5">5 - <?php echo _('Highest') ?></option>
							</select>
						</td>
					</tr>
				</table>
				</fieldset>
				</td>
				</tr>
				<tr><td align="center">
					<button id="createbutton">CREATE CHANGE REQUEST</button>
				</td><td align="center">
					<button id="creatensendbutton">CREATE CHANGE REQUEST AND ADD TO CLIENT</button>
				</td></tr>
			</table>
		</td>
		</tr>
		</table>
    </body>
</html>
