# $Id: Makefile 7424 2010-05-21 08:11:34Z vargenau $
#
# themes/SpaceWiki/Makefile
#
# minify CSS and JS
#

CSS_SRC = SpaceWiki.css
CSS_FILES = $(patsubst %.css,%-min.css,$(CSS_SRC))

all	: css

include ../Makefile.global
