#! /usr/bin/php
<?php
/**
 * GForge Cron Job
 *
 * The rest Copyright 2002-2005 (c) GForge Team
 * Copyright (C) 2009  Sylvain Beucler
 * Copyright 2012, Franck Villaume - TrivialDev
 * http://fusionforge.org/
 *
 * This file is part of FusionForge.
 *
 * FusionForge is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * FusionForge is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

require dirname(__FILE__).'/../../env.inc.php';
require_once $gfcommon.'include/pre.php';
require $gfcommon.'include/cron_utils.php';

$err='';
$res1 = db_query_params('select userid, user_name from sshkeys, users
					where sshkeys.userid = users.user_id
					and users.status = $1
					and users.unix_status = $2',
			array('A', 'A'));

for ($i = 0; $i < db_numrows($res1); $i++) {
	$userid = db_result($res1, $i, 'userid');
	$username = db_result($res1, $i, 'user_name');
	$res2 = db_query_params('select sshkey from sshkeys, users
						where sshkeys.userid = users.user_id
						and users.status = $1
						and users.unix_status = $2
						and sshkeys.deleted = $3
						and sshkeys.deploy = $4
						and sshkeys.userid = $5',
				array('A', 'A', 0, 0, $userid));
	$ssh_key = '';
	while ($arr = db_fetch_array($res2)) {
		$ssh_key .= $arr['sshkey']."\n";
	}
	
	$dir = forge_get_config('homedir_prefix').'/'.$username;
	if (util_is_root_dir($dir)) {
		$err .= "Error! homedir_prefix/username Points To Root Directory!";
		continue;
	}
	$uid = $userid;
	$uid += 1000;

	$ssh_dir = $dir.'/.ssh';
	if (!is_dir($ssh_dir)) {
		mkdir($ssh_dir, 0755);
	}

	# Set the effective uid/gid to this user, so as to avoid symlink attacks
	$userinfo = posix_getpwnam($username);
	posix_setegid($userinfo['gid']);
	posix_seteuid($userinfo['uid']);
	$h8 = fopen($ssh_dir."/authorized_keys", "w");
	fwrite($h8, '# This file is automatically generated from your account settings.'."\n");
	fwrite($h8, $ssh_key);
	fclose($h8);
	posix_seteuid(0);
	posix_setegid(0);
	chown($dir, $username);
	chgrp($dir, 'users');
	chown($ssh_dir, $username);
	chgrp($ssh_dir, 'users');
	chmod($ssh_dir.'/authorized_keys', 0644);
	chown($ssh_dir.'/authorized_keys', $username);
	chgrp($ssh_dir.'/authorized_keys', 'users');

	db_query_params('update sshkeys set deploy = $1 where userid = $2 and deploy = $3',
			array(1, $userid, 0));
	db_query_params('delete from sshkeys where userid = $1 and deleted = $2',
			array($userid, 1));
}

cron_entry(15,$err);

?>
