# $Id: Makefile 7351 2010-04-27 01:44:31Z vargenau $
#
# themes/Wordpress/Makefile
#
# minify CSS and JS
#

CSS_SRC = Wordpress.css
CSS_FILES = $(patsubst %.css,%-min.css,$(CSS_SRC))

all	: css

include ../Makefile.global
