begin;
alter table user_group drop column dead1;
alter table user_group drop column dead2;
alter table user_group drop column dead3;
commit;
begin;
alter table groups drop column dead1;
alter table groups drop column dead2;
alter table groups drop column dead3;
alter table groups drop column dead4;
alter table groups drop column dead5;
alter table groups drop column dead6;
alter table groups drop column dead7;
alter table groups drop column dead8;
alter table groups drop column dead9;
alter table groups drop column dead10;
alter table groups drop column dead11;
alter table groups drop column dead12;
alter table groups drop column dead13;
commit;
