update users set theme_id = (select theme_id from themes where dirname = 'gforge') where theme_id = (select theme_id from themes where dirname = 'osx');
update users set theme_id = (select theme_id from themes where dirname = 'gforge') where theme_id = (select theme_id from themes where dirname = 'gforge-classic');
update users set theme_id = (select theme_id from themes where dirname = 'gforge') where theme_id = (select theme_id from themes where dirname = 'gforge-simple-theme');
update users set theme_id = (select theme_id from themes where dirname = 'gforge') where theme_id = (select theme_id from themes where dirname = 'lite');
update users set theme_id = (select theme_id from themes where dirname = 'gforge') where theme_id = (select theme_id from themes where dirname = 'ultralite');
delete from themes where dirname = 'osx';
delete from themes where dirname = 'gforge-classic';
delete from themes where dirname = 'gforge-simple-theme';
delete from themes where dirname = 'lite';
delete from themes where dirname = 'ultralite';
insert into themes (dirname,fullname,enabled) values ('funky','Funky','t');
