ALTER TABLE stats_agg_site_by_group DROP CONSTRAINT IF EXISTS stats_agg_site_by_group_group_id_fkey;
ALTER TABLE stats_agg_logo_by_group DROP CONSTRAINT IF EXISTS stats_agg_logo_by_group_group_id_fkey;
