ALTER TABLE GROUPS ADD COLUMN send_all_frs INT;
ALTER TABLE GROUPS ALTER COLUMN send_all_frs SET DEFAULT 0;
UPDATE GROUPS SET send_all_frs = 0;
ALTER TABLE GROUPS ADD COLUMN new_frs_address TEXT;
ALTER TABLE GROUPS ALTER COLUMN new_frs_address SET DEFAULT '';
UPDATE GROUPS SET new_frs_address = '';
