<?php


  /* 
   * This file is (c) Copyright 2009 by Madhumita DHAR, Institut
   * TELECOM
   *
   * Use, modification, redistribution of this software are subject to
   * the terms of the NEW BSD License, whose text can be found in the
   * 'COPYING' file that is distributed along with the software archive.
   *
   * Thus you may use it at your own risk, of course !
   *
   * This program has been developed in the frame of the HELIOS
   * project with financial support of its funders.
   *
   */

$json = array("oslc_cm:Error" => array(	"oslc_cm:statusCode"	=> (string)$this->code,
										"oslc_cm:message"		=> (string)$this->exception->getMessage()));

print str_replace("\/", "/", Zend_Json::prettyPrint(Zend_Json::encode($json)));
?>
