/* soapServerLib.c
   Generated by gSOAP 2.3 rev 1 from Gforge.h
   Copyright (C) 2001-2003 Genivia inc.
   All Rights Reserved.
*/
#define WITH_NOGLOBAL
#define SOAP_FMAC3 static
#include "soapC.c"
#include "soapServer.c"

/* end of soapServerLib.c */
