/* soapH.h
   Generated by gSOAP 2.3 rev 1 from SoapAPI.h
   Copyright (C) 2001-2003 Genivia inc.
   All Rights Reserved.
*/
#ifndef soapH_H
#define soapH_H
#include "soapStub.h"

SOAP_BEGIN_NAMESPACE(soap)

SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
SOAP_FMAC3 void * SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putattachments(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getattachments(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);

SOAP_FMAC1 void SOAP_FMAC2 soap_destroy(struct soap*);

SOAP_FMAC1 void SOAP_FMAC2 soap_delete(struct soap*, void*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_byte(struct soap*, char const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (2)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_int(struct soap*, int const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_tns__getNumberOfHostedProjectsResponse
#define SOAP_TYPE_tns__getNumberOfHostedProjectsResponse (3)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__getNumberOfHostedProjectsResponse(struct soap*, const char*, int, const tns__getNumberOfHostedProjectsResponse *, const char*);
SOAP_FMAC3 tns__getNumberOfHostedProjectsResponse * SOAP_FMAC4 soap_get_tns__getNumberOfHostedProjectsResponse(struct soap*, tns__getNumberOfHostedProjectsResponse *, const char*, const char*);
SOAP_FMAC3 tns__getNumberOfHostedProjectsResponse * SOAP_FMAC4 soap_in_tns__getNumberOfHostedProjectsResponse(struct soap*, const char*, tns__getNumberOfHostedProjectsResponse *, const char*);

SOAP_FMAC3 tns__getNumberOfHostedProjectsResponse * SOAP_FMAC4 soap_new_tns__getNumberOfHostedProjectsResponse(struct soap*, int);

SOAP_FMAC3 void SOAP_FMAC4 soap_delete_tns__getNumberOfHostedProjectsResponse(struct soap*, tns__getNumberOfHostedProjectsResponse*);
SOAP_FMAC3 tns__getNumberOfHostedProjectsResponse * SOAP_FMAC4 soap_instantiate_tns__getNumberOfHostedProjectsResponse(struct soap*, int, const char*, const char*, size_t*);

#ifndef SOAP_TYPE_tns__helloResponse
#define SOAP_TYPE_tns__helloResponse (4)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__helloResponse(struct soap*, const char*, int, const tns__helloResponse *, const char*);
SOAP_FMAC3 tns__helloResponse * SOAP_FMAC4 soap_get_tns__helloResponse(struct soap*, tns__helloResponse *, const char*, const char*);
SOAP_FMAC3 tns__helloResponse * SOAP_FMAC4 soap_in_tns__helloResponse(struct soap*, const char*, tns__helloResponse *, const char*);

SOAP_FMAC3 tns__helloResponse * SOAP_FMAC4 soap_new_tns__helloResponse(struct soap*, int);

SOAP_FMAC3 void SOAP_FMAC4 soap_delete_tns__helloResponse(struct soap*, tns__helloResponse*);
SOAP_FMAC3 tns__helloResponse * SOAP_FMAC4 soap_instantiate_tns__helloResponse(struct soap*, int, const char*, const char*, size_t*);

#ifndef SOAP_TYPE_tns__bugAddResponse
#define SOAP_TYPE_tns__bugAddResponse (5)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__bugAddResponse(struct soap*, const char*, int, const tns__bugAddResponse *, const char*);
SOAP_FMAC3 tns__bugAddResponse * SOAP_FMAC4 soap_get_tns__bugAddResponse(struct soap*, tns__bugAddResponse *, const char*, const char*);
SOAP_FMAC3 tns__bugAddResponse * SOAP_FMAC4 soap_in_tns__bugAddResponse(struct soap*, const char*, tns__bugAddResponse *, const char*);

SOAP_FMAC3 tns__bugAddResponse * SOAP_FMAC4 soap_new_tns__bugAddResponse(struct soap*, int);

SOAP_FMAC3 void SOAP_FMAC4 soap_delete_tns__bugAddResponse(struct soap*, tns__bugAddResponse*);
SOAP_FMAC3 tns__bugAddResponse * SOAP_FMAC4 soap_instantiate_tns__bugAddResponse(struct soap*, int, const char*, const char*, size_t*);

#ifndef SOAP_TYPE_tns__bugListResponse
#define SOAP_TYPE_tns__bugListResponse (6)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__bugListResponse(struct soap*, const char*, int, const tns__bugListResponse *, const char*);
SOAP_FMAC3 tns__bugListResponse * SOAP_FMAC4 soap_get_tns__bugListResponse(struct soap*, tns__bugListResponse *, const char*, const char*);
SOAP_FMAC3 tns__bugListResponse * SOAP_FMAC4 soap_in_tns__bugListResponse(struct soap*, const char*, tns__bugListResponse *, const char*);

SOAP_FMAC3 tns__bugListResponse * SOAP_FMAC4 soap_new_tns__bugListResponse(struct soap*, int);

SOAP_FMAC3 void SOAP_FMAC4 soap_delete_tns__bugListResponse(struct soap*, tns__bugListResponse*);
SOAP_FMAC3 tns__bugListResponse * SOAP_FMAC4 soap_instantiate_tns__bugListResponse(struct soap*, int, const char*, const char*, size_t*);

#ifndef SOAP_TYPE_tns__SiteStatsDataPoint
#define SOAP_TYPE_tns__SiteStatsDataPoint (7)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__SiteStatsDataPoint(struct soap*, const char*, int, const tns__SiteStatsDataPoint *, const char*);
SOAP_FMAC3 tns__SiteStatsDataPoint * SOAP_FMAC4 soap_get_tns__SiteStatsDataPoint(struct soap*, tns__SiteStatsDataPoint *, const char*, const char*);
SOAP_FMAC3 tns__SiteStatsDataPoint * SOAP_FMAC4 soap_in_tns__SiteStatsDataPoint(struct soap*, const char*, tns__SiteStatsDataPoint *, const char*);

SOAP_FMAC3 tns__SiteStatsDataPoint * SOAP_FMAC4 soap_new_tns__SiteStatsDataPoint(struct soap*, int);

SOAP_FMAC3 void SOAP_FMAC4 soap_delete_tns__SiteStatsDataPoint(struct soap*, tns__SiteStatsDataPoint*);
SOAP_FMAC3 tns__SiteStatsDataPoint * SOAP_FMAC4 soap_instantiate_tns__SiteStatsDataPoint(struct soap*, int, const char*, const char*, size_t*);

#ifndef SOAP_TYPE_tns__loginResponse
#define SOAP_TYPE_tns__loginResponse (8)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__loginResponse(struct soap*, const char*, int, const tns__loginResponse *, const char*);
SOAP_FMAC3 tns__loginResponse * SOAP_FMAC4 soap_get_tns__loginResponse(struct soap*, tns__loginResponse *, const char*, const char*);
SOAP_FMAC3 tns__loginResponse * SOAP_FMAC4 soap_in_tns__loginResponse(struct soap*, const char*, tns__loginResponse *, const char*);

SOAP_FMAC3 tns__loginResponse * SOAP_FMAC4 soap_new_tns__loginResponse(struct soap*, int);

SOAP_FMAC3 void SOAP_FMAC4 soap_delete_tns__loginResponse(struct soap*, tns__loginResponse*);
SOAP_FMAC3 tns__loginResponse * SOAP_FMAC4 soap_instantiate_tns__loginResponse(struct soap*, int, const char*, const char*, size_t*);

#ifndef SOAP_TYPE_tns__groupResponse
#define SOAP_TYPE_tns__groupResponse (9)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__groupResponse(struct soap*, const char*, int, const tns__groupResponse *, const char*);
SOAP_FMAC3 tns__groupResponse * SOAP_FMAC4 soap_get_tns__groupResponse(struct soap*, tns__groupResponse *, const char*, const char*);
SOAP_FMAC3 tns__groupResponse * SOAP_FMAC4 soap_in_tns__groupResponse(struct soap*, const char*, tns__groupResponse *, const char*);

SOAP_FMAC3 tns__groupResponse * SOAP_FMAC4 soap_new_tns__groupResponse(struct soap*, int);

SOAP_FMAC3 void SOAP_FMAC4 soap_delete_tns__groupResponse(struct soap*, tns__groupResponse*);
SOAP_FMAC3 tns__groupResponse * SOAP_FMAC4 soap_instantiate_tns__groupResponse(struct soap*, int, const char*, const char*, size_t*);

#ifndef SOAP_TYPE_tns__getNumberOfActiveUsersResponse
#define SOAP_TYPE_tns__getNumberOfActiveUsersResponse (10)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__getNumberOfActiveUsersResponse(struct soap*, const char*, int, const tns__getNumberOfActiveUsersResponse *, const char*);
SOAP_FMAC3 tns__getNumberOfActiveUsersResponse * SOAP_FMAC4 soap_get_tns__getNumberOfActiveUsersResponse(struct soap*, tns__getNumberOfActiveUsersResponse *, const char*, const char*);
SOAP_FMAC3 tns__getNumberOfActiveUsersResponse * SOAP_FMAC4 soap_in_tns__getNumberOfActiveUsersResponse(struct soap*, const char*, tns__getNumberOfActiveUsersResponse *, const char*);

SOAP_FMAC3 tns__getNumberOfActiveUsersResponse * SOAP_FMAC4 soap_new_tns__getNumberOfActiveUsersResponse(struct soap*, int);

SOAP_FMAC3 void SOAP_FMAC4 soap_delete_tns__getNumberOfActiveUsersResponse(struct soap*, tns__getNumberOfActiveUsersResponse*);
SOAP_FMAC3 tns__getNumberOfActiveUsersResponse * SOAP_FMAC4 soap_instantiate_tns__getNumberOfActiveUsersResponse(struct soap*, int, const char*, const char*, size_t*);

#ifndef SOAP_TYPE_ArrayOfGroupObject
#define SOAP_TYPE_ArrayOfGroupObject (11)
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ArrayOfGroupObject(struct soap*, const char*, int, const ArrayOfGroupObject *, const char*);
SOAP_FMAC3 ArrayOfGroupObject * SOAP_FMAC4 soap_get_ArrayOfGroupObject(struct soap*, ArrayOfGroupObject *, const char*, const char*);
SOAP_FMAC3 ArrayOfGroupObject * SOAP_FMAC4 soap_in_ArrayOfGroupObject(struct soap*, const char*, ArrayOfGroupObject *, const char*);

SOAP_FMAC3 ArrayOfGroupObject * SOAP_FMAC4 soap_new_ArrayOfGroupObject(struct soap*, int);

SOAP_FMAC3 void SOAP_FMAC4 soap_delete_ArrayOfGroupObject(struct soap*, ArrayOfGroupObject*);
SOAP_FMAC3 ArrayOfGroupObject * SOAP_FMAC4 soap_instantiate_ArrayOfGroupObject(struct soap*, int, const char*, const char*, size_t*);

#ifndef SOAP_TYPE_ArrayOfBug
#define SOAP_TYPE_ArrayOfBug (12)
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ArrayOfBug(struct soap*, const char*, int, const ArrayOfBug *, const char*);
SOAP_FMAC3 ArrayOfBug * SOAP_FMAC4 soap_get_ArrayOfBug(struct soap*, ArrayOfBug *, const char*, const char*);
SOAP_FMAC3 ArrayOfBug * SOAP_FMAC4 soap_in_ArrayOfBug(struct soap*, const char*, ArrayOfBug *, const char*);

SOAP_FMAC3 ArrayOfBug * SOAP_FMAC4 soap_new_ArrayOfBug(struct soap*, int);

SOAP_FMAC3 void SOAP_FMAC4 soap_delete_ArrayOfBug(struct soap*, ArrayOfBug*);
SOAP_FMAC3 ArrayOfBug * SOAP_FMAC4 soap_instantiate_ArrayOfBug(struct soap*, int, const char*, const char*, size_t*);

#ifndef SOAP_TYPE_tns__GroupObject
#define SOAP_TYPE_tns__GroupObject (13)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__GroupObject(struct soap*, const char*, int, const tns__GroupObject *, const char*);
SOAP_FMAC3 tns__GroupObject * SOAP_FMAC4 soap_get_tns__GroupObject(struct soap*, tns__GroupObject *, const char*, const char*);
SOAP_FMAC3 tns__GroupObject * SOAP_FMAC4 soap_in_tns__GroupObject(struct soap*, const char*, tns__GroupObject *, const char*);

SOAP_FMAC3 tns__GroupObject * SOAP_FMAC4 soap_new_tns__GroupObject(struct soap*, int);

SOAP_FMAC3 void SOAP_FMAC4 soap_delete_tns__GroupObject(struct soap*, tns__GroupObject*);
SOAP_FMAC3 tns__GroupObject * SOAP_FMAC4 soap_instantiate_tns__GroupObject(struct soap*, int, const char*, const char*, size_t*);

#ifndef SOAP_TYPE_ArrayOfSiteStatsDataPoint
#define SOAP_TYPE_ArrayOfSiteStatsDataPoint (14)
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ArrayOfSiteStatsDataPoint(struct soap*, const char*, int, const ArrayOfSiteStatsDataPoint *, const char*);
SOAP_FMAC3 ArrayOfSiteStatsDataPoint * SOAP_FMAC4 soap_get_ArrayOfSiteStatsDataPoint(struct soap*, ArrayOfSiteStatsDataPoint *, const char*, const char*);
SOAP_FMAC3 ArrayOfSiteStatsDataPoint * SOAP_FMAC4 soap_in_ArrayOfSiteStatsDataPoint(struct soap*, const char*, ArrayOfSiteStatsDataPoint *, const char*);

SOAP_FMAC3 ArrayOfSiteStatsDataPoint * SOAP_FMAC4 soap_new_ArrayOfSiteStatsDataPoint(struct soap*, int);

SOAP_FMAC3 void SOAP_FMAC4 soap_delete_ArrayOfSiteStatsDataPoint(struct soap*, ArrayOfSiteStatsDataPoint*);
SOAP_FMAC3 ArrayOfSiteStatsDataPoint * SOAP_FMAC4 soap_instantiate_ArrayOfSiteStatsDataPoint(struct soap*, int, const char*, const char*, size_t*);

#ifndef SOAP_TYPE_tns__getSiteStatsResponse
#define SOAP_TYPE_tns__getSiteStatsResponse (15)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__getSiteStatsResponse(struct soap*, const char*, int, const tns__getSiteStatsResponse *, const char*);
SOAP_FMAC3 tns__getSiteStatsResponse * SOAP_FMAC4 soap_get_tns__getSiteStatsResponse(struct soap*, tns__getSiteStatsResponse *, const char*, const char*);
SOAP_FMAC3 tns__getSiteStatsResponse * SOAP_FMAC4 soap_in_tns__getSiteStatsResponse(struct soap*, const char*, tns__getSiteStatsResponse *, const char*);

SOAP_FMAC3 tns__getSiteStatsResponse * SOAP_FMAC4 soap_new_tns__getSiteStatsResponse(struct soap*, int);

SOAP_FMAC3 void SOAP_FMAC4 soap_delete_tns__getSiteStatsResponse(struct soap*, tns__getSiteStatsResponse*);
SOAP_FMAC3 tns__getSiteStatsResponse * SOAP_FMAC4 soap_instantiate_tns__getSiteStatsResponse(struct soap*, int, const char*, const char*, size_t*);

#ifndef SOAP_TYPE_tns__getPublicProjectNamesResponse
#define SOAP_TYPE_tns__getPublicProjectNamesResponse (16)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__getPublicProjectNamesResponse(struct soap*, const char*, int, const tns__getPublicProjectNamesResponse *, const char*);
SOAP_FMAC3 tns__getPublicProjectNamesResponse * SOAP_FMAC4 soap_get_tns__getPublicProjectNamesResponse(struct soap*, tns__getPublicProjectNamesResponse *, const char*, const char*);
SOAP_FMAC3 tns__getPublicProjectNamesResponse * SOAP_FMAC4 soap_in_tns__getPublicProjectNamesResponse(struct soap*, const char*, tns__getPublicProjectNamesResponse *, const char*);

SOAP_FMAC3 tns__getPublicProjectNamesResponse * SOAP_FMAC4 soap_new_tns__getPublicProjectNamesResponse(struct soap*, int);

SOAP_FMAC3 void SOAP_FMAC4 soap_delete_tns__getPublicProjectNamesResponse(struct soap*, tns__getPublicProjectNamesResponse*);
SOAP_FMAC3 tns__getPublicProjectNamesResponse * SOAP_FMAC4 soap_instantiate_tns__getPublicProjectNamesResponse(struct soap*, int, const char*, const char*, size_t*);

#ifndef SOAP_TYPE_tns__logoutResponse
#define SOAP_TYPE_tns__logoutResponse (17)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__logoutResponse(struct soap*, const char*, int, const tns__logoutResponse *, const char*);
SOAP_FMAC3 tns__logoutResponse * SOAP_FMAC4 soap_get_tns__logoutResponse(struct soap*, tns__logoutResponse *, const char*, const char*);
SOAP_FMAC3 tns__logoutResponse * SOAP_FMAC4 soap_in_tns__logoutResponse(struct soap*, const char*, tns__logoutResponse *, const char*);

SOAP_FMAC3 tns__logoutResponse * SOAP_FMAC4 soap_new_tns__logoutResponse(struct soap*, int);

SOAP_FMAC3 void SOAP_FMAC4 soap_delete_tns__logoutResponse(struct soap*, tns__logoutResponse*);
SOAP_FMAC3 tns__logoutResponse * SOAP_FMAC4 soap_instantiate_tns__logoutResponse(struct soap*, int, const char*, const char*, size_t*);

#ifndef SOAP_TYPE_tns__Bug
#define SOAP_TYPE_tns__Bug (18)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__Bug(struct soap*, const char*, int, const tns__Bug *, const char*);
SOAP_FMAC3 tns__Bug * SOAP_FMAC4 soap_get_tns__Bug(struct soap*, tns__Bug *, const char*, const char*);
SOAP_FMAC3 tns__Bug * SOAP_FMAC4 soap_in_tns__Bug(struct soap*, const char*, tns__Bug *, const char*);

SOAP_FMAC3 tns__Bug * SOAP_FMAC4 soap_new_tns__Bug(struct soap*, int);

SOAP_FMAC3 void SOAP_FMAC4 soap_delete_tns__Bug(struct soap*, tns__Bug*);
SOAP_FMAC3 tns__Bug * SOAP_FMAC4 soap_instantiate_tns__Bug(struct soap*, int, const char*, const char*, size_t*);

#ifndef SOAP_TYPE_tns__bugFetchResponse
#define SOAP_TYPE_tns__bugFetchResponse (19)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__bugFetchResponse(struct soap*, const char*, int, const tns__bugFetchResponse *, const char*);
SOAP_FMAC3 tns__bugFetchResponse * SOAP_FMAC4 soap_get_tns__bugFetchResponse(struct soap*, tns__bugFetchResponse *, const char*, const char*);
SOAP_FMAC3 tns__bugFetchResponse * SOAP_FMAC4 soap_in_tns__bugFetchResponse(struct soap*, const char*, tns__bugFetchResponse *, const char*);

SOAP_FMAC3 tns__bugFetchResponse * SOAP_FMAC4 soap_new_tns__bugFetchResponse(struct soap*, int);

SOAP_FMAC3 void SOAP_FMAC4 soap_delete_tns__bugFetchResponse(struct soap*, tns__bugFetchResponse*);
SOAP_FMAC3 tns__bugFetchResponse * SOAP_FMAC4 soap_instantiate_tns__bugFetchResponse(struct soap*, int, const char*, const char*, size_t*);

#ifndef SOAP_TYPE_tns__ArrayOfstring
#define SOAP_TYPE_tns__ArrayOfstring (20)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__ArrayOfstring(struct soap*, const char*, int, const tns__ArrayOfstring *, const char*);
SOAP_FMAC3 tns__ArrayOfstring * SOAP_FMAC4 soap_get_tns__ArrayOfstring(struct soap*, tns__ArrayOfstring *, const char*, const char*);
SOAP_FMAC3 tns__ArrayOfstring * SOAP_FMAC4 soap_in_tns__ArrayOfstring(struct soap*, const char*, tns__ArrayOfstring *, const char*);

SOAP_FMAC3 tns__ArrayOfstring * SOAP_FMAC4 soap_new_tns__ArrayOfstring(struct soap*, int);

SOAP_FMAC3 void SOAP_FMAC4 soap_delete_tns__ArrayOfstring(struct soap*, tns__ArrayOfstring*);
SOAP_FMAC3 tns__ArrayOfstring * SOAP_FMAC4 soap_instantiate_tns__ArrayOfstring(struct soap*, int, const char*, const char*, size_t*);

#ifndef SOAP_TYPE_tns__userResponse
#define SOAP_TYPE_tns__userResponse (21)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__userResponse(struct soap*, const char*, int, const tns__userResponse *, const char*);
SOAP_FMAC3 tns__userResponse * SOAP_FMAC4 soap_get_tns__userResponse(struct soap*, tns__userResponse *, const char*, const char*);
SOAP_FMAC3 tns__userResponse * SOAP_FMAC4 soap_in_tns__userResponse(struct soap*, const char*, tns__userResponse *, const char*);

SOAP_FMAC3 tns__userResponse * SOAP_FMAC4 soap_new_tns__userResponse(struct soap*, int);

SOAP_FMAC3 void SOAP_FMAC4 soap_delete_tns__userResponse(struct soap*, tns__userResponse*);
SOAP_FMAC3 tns__userResponse * SOAP_FMAC4 soap_instantiate_tns__userResponse(struct soap*, int, const char*, const char*, size_t*);

#ifndef SOAP_TYPE_tns__bugUpdateResponse
#define SOAP_TYPE_tns__bugUpdateResponse (22)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__bugUpdateResponse(struct soap*, const char*, int, const tns__bugUpdateResponse *, const char*);
SOAP_FMAC3 tns__bugUpdateResponse * SOAP_FMAC4 soap_get_tns__bugUpdateResponse(struct soap*, tns__bugUpdateResponse *, const char*, const char*);
SOAP_FMAC3 tns__bugUpdateResponse * SOAP_FMAC4 soap_in_tns__bugUpdateResponse(struct soap*, const char*, tns__bugUpdateResponse *, const char*);

SOAP_FMAC3 tns__bugUpdateResponse * SOAP_FMAC4 soap_new_tns__bugUpdateResponse(struct soap*, int);

SOAP_FMAC3 void SOAP_FMAC4 soap_delete_tns__bugUpdateResponse(struct soap*, tns__bugUpdateResponse*);
SOAP_FMAC3 tns__bugUpdateResponse * SOAP_FMAC4 soap_instantiate_tns__bugUpdateResponse(struct soap*, int, const char*, const char*, size_t*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#endif

#ifndef SOAP_TYPE_tns__bugFetch
#define SOAP_TYPE_tns__bugFetch (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__bugFetch(struct soap*, struct tns__bugFetch const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tns__bugFetch(struct soap*, const struct tns__bugFetch *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__bugFetch(struct soap*, struct tns__bugFetch *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__bugFetch(struct soap*, struct tns__bugFetch *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__bugFetch(struct soap*, const char*, int, const struct tns__bugFetch *, const char*);
SOAP_FMAC3 struct tns__bugFetch * SOAP_FMAC4 soap_get_tns__bugFetch(struct soap*, struct tns__bugFetch *, const char*, const char*);
SOAP_FMAC3 struct tns__bugFetch * SOAP_FMAC4 soap_in_tns__bugFetch(struct soap*, const char*, struct tns__bugFetch *, const char*);

#ifndef SOAP_TYPE_tns__getNumberOfHostedProjects
#define SOAP_TYPE_tns__getNumberOfHostedProjects (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__getNumberOfHostedProjects(struct soap*, struct tns__getNumberOfHostedProjects const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tns__getNumberOfHostedProjects(struct soap*, const struct tns__getNumberOfHostedProjects *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__getNumberOfHostedProjects(struct soap*, struct tns__getNumberOfHostedProjects *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__getNumberOfHostedProjects(struct soap*, struct tns__getNumberOfHostedProjects *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__getNumberOfHostedProjects(struct soap*, const char*, int, const struct tns__getNumberOfHostedProjects *, const char*);
SOAP_FMAC3 struct tns__getNumberOfHostedProjects * SOAP_FMAC4 soap_get_tns__getNumberOfHostedProjects(struct soap*, struct tns__getNumberOfHostedProjects *, const char*, const char*);
SOAP_FMAC3 struct tns__getNumberOfHostedProjects * SOAP_FMAC4 soap_in_tns__getNumberOfHostedProjects(struct soap*, const char*, struct tns__getNumberOfHostedProjects *, const char*);

#ifndef SOAP_TYPE_tns__bugAdd
#define SOAP_TYPE_tns__bugAdd (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__bugAdd(struct soap*, struct tns__bugAdd const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tns__bugAdd(struct soap*, const struct tns__bugAdd *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__bugAdd(struct soap*, struct tns__bugAdd *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__bugAdd(struct soap*, struct tns__bugAdd *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__bugAdd(struct soap*, const char*, int, const struct tns__bugAdd *, const char*);
SOAP_FMAC3 struct tns__bugAdd * SOAP_FMAC4 soap_get_tns__bugAdd(struct soap*, struct tns__bugAdd *, const char*, const char*);
SOAP_FMAC3 struct tns__bugAdd * SOAP_FMAC4 soap_in_tns__bugAdd(struct soap*, const char*, struct tns__bugAdd *, const char*);

#ifndef SOAP_TYPE_tns__login
#define SOAP_TYPE_tns__login (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__login(struct soap*, struct tns__login const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tns__login(struct soap*, const struct tns__login *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__login(struct soap*, struct tns__login *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__login(struct soap*, struct tns__login *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__login(struct soap*, const char*, int, const struct tns__login *, const char*);
SOAP_FMAC3 struct tns__login * SOAP_FMAC4 soap_get_tns__login(struct soap*, struct tns__login *, const char*, const char*);
SOAP_FMAC3 struct tns__login * SOAP_FMAC4 soap_in_tns__login(struct soap*, const char*, struct tns__login *, const char*);

#ifndef SOAP_TYPE_tns__getSiteStats
#define SOAP_TYPE_tns__getSiteStats (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__getSiteStats(struct soap*, struct tns__getSiteStats const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tns__getSiteStats(struct soap*, const struct tns__getSiteStats *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__getSiteStats(struct soap*, struct tns__getSiteStats *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__getSiteStats(struct soap*, struct tns__getSiteStats *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__getSiteStats(struct soap*, const char*, int, const struct tns__getSiteStats *, const char*);
SOAP_FMAC3 struct tns__getSiteStats * SOAP_FMAC4 soap_get_tns__getSiteStats(struct soap*, struct tns__getSiteStats *, const char*, const char*);
SOAP_FMAC3 struct tns__getSiteStats * SOAP_FMAC4 soap_in_tns__getSiteStats(struct soap*, const char*, struct tns__getSiteStats *, const char*);

#ifndef SOAP_TYPE_tns__getPublicProjectNames
#define SOAP_TYPE_tns__getPublicProjectNames (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__getPublicProjectNames(struct soap*, struct tns__getPublicProjectNames const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tns__getPublicProjectNames(struct soap*, const struct tns__getPublicProjectNames *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__getPublicProjectNames(struct soap*, struct tns__getPublicProjectNames *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__getPublicProjectNames(struct soap*, struct tns__getPublicProjectNames *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__getPublicProjectNames(struct soap*, const char*, int, const struct tns__getPublicProjectNames *, const char*);
SOAP_FMAC3 struct tns__getPublicProjectNames * SOAP_FMAC4 soap_get_tns__getPublicProjectNames(struct soap*, struct tns__getPublicProjectNames *, const char*, const char*);
SOAP_FMAC3 struct tns__getPublicProjectNames * SOAP_FMAC4 soap_in_tns__getPublicProjectNames(struct soap*, const char*, struct tns__getPublicProjectNames *, const char*);

#ifndef SOAP_TYPE_tns__group
#define SOAP_TYPE_tns__group (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__group(struct soap*, struct tns__group const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tns__group(struct soap*, const struct tns__group *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__group(struct soap*, struct tns__group *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__group(struct soap*, struct tns__group *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__group(struct soap*, const char*, int, const struct tns__group *, const char*);
SOAP_FMAC3 struct tns__group * SOAP_FMAC4 soap_get_tns__group(struct soap*, struct tns__group *, const char*, const char*);
SOAP_FMAC3 struct tns__group * SOAP_FMAC4 soap_in_tns__group(struct soap*, const char*, struct tns__group *, const char*);

#ifndef SOAP_TYPE_tns__bugUpdate
#define SOAP_TYPE_tns__bugUpdate (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__bugUpdate(struct soap*, struct tns__bugUpdate const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tns__bugUpdate(struct soap*, const struct tns__bugUpdate *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__bugUpdate(struct soap*, struct tns__bugUpdate *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__bugUpdate(struct soap*, struct tns__bugUpdate *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__bugUpdate(struct soap*, const char*, int, const struct tns__bugUpdate *, const char*);
SOAP_FMAC3 struct tns__bugUpdate * SOAP_FMAC4 soap_get_tns__bugUpdate(struct soap*, struct tns__bugUpdate *, const char*, const char*);
SOAP_FMAC3 struct tns__bugUpdate * SOAP_FMAC4 soap_in_tns__bugUpdate(struct soap*, const char*, struct tns__bugUpdate *, const char*);

#ifndef SOAP_TYPE_tns__bugList
#define SOAP_TYPE_tns__bugList (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__bugList(struct soap*, struct tns__bugList const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tns__bugList(struct soap*, const struct tns__bugList *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__bugList(struct soap*, struct tns__bugList *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__bugList(struct soap*, struct tns__bugList *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__bugList(struct soap*, const char*, int, const struct tns__bugList *, const char*);
SOAP_FMAC3 struct tns__bugList * SOAP_FMAC4 soap_get_tns__bugList(struct soap*, struct tns__bugList *, const char*, const char*);
SOAP_FMAC3 struct tns__bugList * SOAP_FMAC4 soap_in_tns__bugList(struct soap*, const char*, struct tns__bugList *, const char*);

#ifndef SOAP_TYPE_tns__getNumberOfActiveUsers
#define SOAP_TYPE_tns__getNumberOfActiveUsers (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__getNumberOfActiveUsers(struct soap*, struct tns__getNumberOfActiveUsers const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tns__getNumberOfActiveUsers(struct soap*, const struct tns__getNumberOfActiveUsers *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__getNumberOfActiveUsers(struct soap*, struct tns__getNumberOfActiveUsers *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__getNumberOfActiveUsers(struct soap*, struct tns__getNumberOfActiveUsers *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__getNumberOfActiveUsers(struct soap*, const char*, int, const struct tns__getNumberOfActiveUsers *, const char*);
SOAP_FMAC3 struct tns__getNumberOfActiveUsers * SOAP_FMAC4 soap_get_tns__getNumberOfActiveUsers(struct soap*, struct tns__getNumberOfActiveUsers *, const char*, const char*);
SOAP_FMAC3 struct tns__getNumberOfActiveUsers * SOAP_FMAC4 soap_in_tns__getNumberOfActiveUsers(struct soap*, const char*, struct tns__getNumberOfActiveUsers *, const char*);

#ifndef SOAP_TYPE_tns__hello
#define SOAP_TYPE_tns__hello (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__hello(struct soap*, struct tns__hello const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tns__hello(struct soap*, const struct tns__hello *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__hello(struct soap*, struct tns__hello *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__hello(struct soap*, struct tns__hello *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__hello(struct soap*, const char*, int, const struct tns__hello *, const char*);
SOAP_FMAC3 struct tns__hello * SOAP_FMAC4 soap_get_tns__hello(struct soap*, struct tns__hello *, const char*, const char*);
SOAP_FMAC3 struct tns__hello * SOAP_FMAC4 soap_in_tns__hello(struct soap*, const char*, struct tns__hello *, const char*);

#ifndef SOAP_TYPE_tns__logout
#define SOAP_TYPE_tns__logout (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__logout(struct soap*, struct tns__logout const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tns__logout(struct soap*, const struct tns__logout *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__logout(struct soap*, struct tns__logout *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__logout(struct soap*, struct tns__logout *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__logout(struct soap*, const char*, int, const struct tns__logout *, const char*);
SOAP_FMAC3 struct tns__logout * SOAP_FMAC4 soap_get_tns__logout(struct soap*, struct tns__logout *, const char*, const char*);
SOAP_FMAC3 struct tns__logout * SOAP_FMAC4 soap_in_tns__logout(struct soap*, const char*, struct tns__logout *, const char*);

#ifndef SOAP_TYPE_tns__user
#define SOAP_TYPE_tns__user (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__user(struct soap*, struct tns__user const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tns__user(struct soap*, const struct tns__user *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__user(struct soap*, struct tns__user *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__user(struct soap*, struct tns__user *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__user(struct soap*, const char*, int, const struct tns__user *, const char*);
SOAP_FMAC3 struct tns__user * SOAP_FMAC4 soap_get_tns__user(struct soap*, struct tns__user *, const char*, const char*);
SOAP_FMAC3 struct tns__user * SOAP_FMAC4 soap_in_tns__user(struct soap*, const char*, struct tns__user *, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_PointerTotns__bugFetchResponse
#define SOAP_TYPE_PointerTotns__bugFetchResponse (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotns__bugFetchResponse(struct soap*, tns__bugFetchResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTotns__bugFetchResponse(struct soap*, tns__bugFetchResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTotns__bugFetchResponse(struct soap*, tns__bugFetchResponse **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotns__bugFetchResponse(struct soap*, tns__bugFetchResponse **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotns__bugFetchResponse(struct soap*, const char *, int, tns__bugFetchResponse *const*, const char *);
SOAP_FMAC3 tns__bugFetchResponse ** SOAP_FMAC4 soap_get_PointerTotns__bugFetchResponse(struct soap*, tns__bugFetchResponse **, const char*, const char*);
SOAP_FMAC3 tns__bugFetchResponse ** SOAP_FMAC4 soap_in_PointerTotns__bugFetchResponse(struct soap*, const char*, tns__bugFetchResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotns__getNumberOfHostedProjectsResponse
#define SOAP_TYPE_PointerTotns__getNumberOfHostedProjectsResponse (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotns__getNumberOfHostedProjectsResponse(struct soap*, tns__getNumberOfHostedProjectsResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTotns__getNumberOfHostedProjectsResponse(struct soap*, tns__getNumberOfHostedProjectsResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTotns__getNumberOfHostedProjectsResponse(struct soap*, tns__getNumberOfHostedProjectsResponse **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotns__getNumberOfHostedProjectsResponse(struct soap*, tns__getNumberOfHostedProjectsResponse **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotns__getNumberOfHostedProjectsResponse(struct soap*, const char *, int, tns__getNumberOfHostedProjectsResponse *const*, const char *);
SOAP_FMAC3 tns__getNumberOfHostedProjectsResponse ** SOAP_FMAC4 soap_get_PointerTotns__getNumberOfHostedProjectsResponse(struct soap*, tns__getNumberOfHostedProjectsResponse **, const char*, const char*);
SOAP_FMAC3 tns__getNumberOfHostedProjectsResponse ** SOAP_FMAC4 soap_in_PointerTotns__getNumberOfHostedProjectsResponse(struct soap*, const char*, tns__getNumberOfHostedProjectsResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotns__bugAddResponse
#define SOAP_TYPE_PointerTotns__bugAddResponse (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotns__bugAddResponse(struct soap*, tns__bugAddResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTotns__bugAddResponse(struct soap*, tns__bugAddResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTotns__bugAddResponse(struct soap*, tns__bugAddResponse **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotns__bugAddResponse(struct soap*, tns__bugAddResponse **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotns__bugAddResponse(struct soap*, const char *, int, tns__bugAddResponse *const*, const char *);
SOAP_FMAC3 tns__bugAddResponse ** SOAP_FMAC4 soap_get_PointerTotns__bugAddResponse(struct soap*, tns__bugAddResponse **, const char*, const char*);
SOAP_FMAC3 tns__bugAddResponse ** SOAP_FMAC4 soap_in_PointerTotns__bugAddResponse(struct soap*, const char*, tns__bugAddResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotns__loginResponse
#define SOAP_TYPE_PointerTotns__loginResponse (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotns__loginResponse(struct soap*, tns__loginResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTotns__loginResponse(struct soap*, tns__loginResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTotns__loginResponse(struct soap*, tns__loginResponse **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotns__loginResponse(struct soap*, tns__loginResponse **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotns__loginResponse(struct soap*, const char *, int, tns__loginResponse *const*, const char *);
SOAP_FMAC3 tns__loginResponse ** SOAP_FMAC4 soap_get_PointerTotns__loginResponse(struct soap*, tns__loginResponse **, const char*, const char*);
SOAP_FMAC3 tns__loginResponse ** SOAP_FMAC4 soap_in_PointerTotns__loginResponse(struct soap*, const char*, tns__loginResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotns__getSiteStatsResponse
#define SOAP_TYPE_PointerTotns__getSiteStatsResponse (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotns__getSiteStatsResponse(struct soap*, tns__getSiteStatsResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTotns__getSiteStatsResponse(struct soap*, tns__getSiteStatsResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTotns__getSiteStatsResponse(struct soap*, tns__getSiteStatsResponse **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotns__getSiteStatsResponse(struct soap*, tns__getSiteStatsResponse **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotns__getSiteStatsResponse(struct soap*, const char *, int, tns__getSiteStatsResponse *const*, const char *);
SOAP_FMAC3 tns__getSiteStatsResponse ** SOAP_FMAC4 soap_get_PointerTotns__getSiteStatsResponse(struct soap*, tns__getSiteStatsResponse **, const char*, const char*);
SOAP_FMAC3 tns__getSiteStatsResponse ** SOAP_FMAC4 soap_in_PointerTotns__getSiteStatsResponse(struct soap*, const char*, tns__getSiteStatsResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotns__getPublicProjectNamesResponse
#define SOAP_TYPE_PointerTotns__getPublicProjectNamesResponse (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotns__getPublicProjectNamesResponse(struct soap*, tns__getPublicProjectNamesResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTotns__getPublicProjectNamesResponse(struct soap*, tns__getPublicProjectNamesResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTotns__getPublicProjectNamesResponse(struct soap*, tns__getPublicProjectNamesResponse **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotns__getPublicProjectNamesResponse(struct soap*, tns__getPublicProjectNamesResponse **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotns__getPublicProjectNamesResponse(struct soap*, const char *, int, tns__getPublicProjectNamesResponse *const*, const char *);
SOAP_FMAC3 tns__getPublicProjectNamesResponse ** SOAP_FMAC4 soap_get_PointerTotns__getPublicProjectNamesResponse(struct soap*, tns__getPublicProjectNamesResponse **, const char*, const char*);
SOAP_FMAC3 tns__getPublicProjectNamesResponse ** SOAP_FMAC4 soap_in_PointerTotns__getPublicProjectNamesResponse(struct soap*, const char*, tns__getPublicProjectNamesResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotns__groupResponse
#define SOAP_TYPE_PointerTotns__groupResponse (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotns__groupResponse(struct soap*, tns__groupResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTotns__groupResponse(struct soap*, tns__groupResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTotns__groupResponse(struct soap*, tns__groupResponse **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotns__groupResponse(struct soap*, tns__groupResponse **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotns__groupResponse(struct soap*, const char *, int, tns__groupResponse *const*, const char *);
SOAP_FMAC3 tns__groupResponse ** SOAP_FMAC4 soap_get_PointerTotns__groupResponse(struct soap*, tns__groupResponse **, const char*, const char*);
SOAP_FMAC3 tns__groupResponse ** SOAP_FMAC4 soap_in_PointerTotns__groupResponse(struct soap*, const char*, tns__groupResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotns__bugUpdateResponse
#define SOAP_TYPE_PointerTotns__bugUpdateResponse (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotns__bugUpdateResponse(struct soap*, tns__bugUpdateResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTotns__bugUpdateResponse(struct soap*, tns__bugUpdateResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTotns__bugUpdateResponse(struct soap*, tns__bugUpdateResponse **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotns__bugUpdateResponse(struct soap*, tns__bugUpdateResponse **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotns__bugUpdateResponse(struct soap*, const char *, int, tns__bugUpdateResponse *const*, const char *);
SOAP_FMAC3 tns__bugUpdateResponse ** SOAP_FMAC4 soap_get_PointerTotns__bugUpdateResponse(struct soap*, tns__bugUpdateResponse **, const char*, const char*);
SOAP_FMAC3 tns__bugUpdateResponse ** SOAP_FMAC4 soap_in_PointerTotns__bugUpdateResponse(struct soap*, const char*, tns__bugUpdateResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotns__bugListResponse
#define SOAP_TYPE_PointerTotns__bugListResponse (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotns__bugListResponse(struct soap*, tns__bugListResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTotns__bugListResponse(struct soap*, tns__bugListResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTotns__bugListResponse(struct soap*, tns__bugListResponse **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotns__bugListResponse(struct soap*, tns__bugListResponse **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotns__bugListResponse(struct soap*, const char *, int, tns__bugListResponse *const*, const char *);
SOAP_FMAC3 tns__bugListResponse ** SOAP_FMAC4 soap_get_PointerTotns__bugListResponse(struct soap*, tns__bugListResponse **, const char*, const char*);
SOAP_FMAC3 tns__bugListResponse ** SOAP_FMAC4 soap_in_PointerTotns__bugListResponse(struct soap*, const char*, tns__bugListResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotns__getNumberOfActiveUsersResponse
#define SOAP_TYPE_PointerTotns__getNumberOfActiveUsersResponse (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotns__getNumberOfActiveUsersResponse(struct soap*, tns__getNumberOfActiveUsersResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTotns__getNumberOfActiveUsersResponse(struct soap*, tns__getNumberOfActiveUsersResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTotns__getNumberOfActiveUsersResponse(struct soap*, tns__getNumberOfActiveUsersResponse **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotns__getNumberOfActiveUsersResponse(struct soap*, tns__getNumberOfActiveUsersResponse **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotns__getNumberOfActiveUsersResponse(struct soap*, const char *, int, tns__getNumberOfActiveUsersResponse *const*, const char *);
SOAP_FMAC3 tns__getNumberOfActiveUsersResponse ** SOAP_FMAC4 soap_get_PointerTotns__getNumberOfActiveUsersResponse(struct soap*, tns__getNumberOfActiveUsersResponse **, const char*, const char*);
SOAP_FMAC3 tns__getNumberOfActiveUsersResponse ** SOAP_FMAC4 soap_in_PointerTotns__getNumberOfActiveUsersResponse(struct soap*, const char*, tns__getNumberOfActiveUsersResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotns__helloResponse
#define SOAP_TYPE_PointerTotns__helloResponse (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotns__helloResponse(struct soap*, tns__helloResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTotns__helloResponse(struct soap*, tns__helloResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTotns__helloResponse(struct soap*, tns__helloResponse **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotns__helloResponse(struct soap*, tns__helloResponse **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotns__helloResponse(struct soap*, const char *, int, tns__helloResponse *const*, const char *);
SOAP_FMAC3 tns__helloResponse ** SOAP_FMAC4 soap_get_PointerTotns__helloResponse(struct soap*, tns__helloResponse **, const char*, const char*);
SOAP_FMAC3 tns__helloResponse ** SOAP_FMAC4 soap_in_PointerTotns__helloResponse(struct soap*, const char*, tns__helloResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotns__logoutResponse
#define SOAP_TYPE_PointerTotns__logoutResponse (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotns__logoutResponse(struct soap*, tns__logoutResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTotns__logoutResponse(struct soap*, tns__logoutResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTotns__logoutResponse(struct soap*, tns__logoutResponse **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotns__logoutResponse(struct soap*, tns__logoutResponse **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotns__logoutResponse(struct soap*, const char *, int, tns__logoutResponse *const*, const char *);
SOAP_FMAC3 tns__logoutResponse ** SOAP_FMAC4 soap_get_PointerTotns__logoutResponse(struct soap*, tns__logoutResponse **, const char*, const char*);
SOAP_FMAC3 tns__logoutResponse ** SOAP_FMAC4 soap_in_PointerTotns__logoutResponse(struct soap*, const char*, tns__logoutResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotns__userResponse
#define SOAP_TYPE_PointerTotns__userResponse (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotns__userResponse(struct soap*, tns__userResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTotns__userResponse(struct soap*, tns__userResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTotns__userResponse(struct soap*, tns__userResponse **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotns__userResponse(struct soap*, tns__userResponse **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotns__userResponse(struct soap*, const char *, int, tns__userResponse *const*, const char *);
SOAP_FMAC3 tns__userResponse ** SOAP_FMAC4 soap_get_PointerTotns__userResponse(struct soap*, tns__userResponse **, const char*, const char*);
SOAP_FMAC3 tns__userResponse ** SOAP_FMAC4 soap_in_PointerTotns__userResponse(struct soap*, const char*, tns__userResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotns__SiteStatsDataPoint
#define SOAP_TYPE_PointerTotns__SiteStatsDataPoint (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotns__SiteStatsDataPoint(struct soap*, tns__SiteStatsDataPoint *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTotns__SiteStatsDataPoint(struct soap*, tns__SiteStatsDataPoint *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTotns__SiteStatsDataPoint(struct soap*, tns__SiteStatsDataPoint **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotns__SiteStatsDataPoint(struct soap*, tns__SiteStatsDataPoint **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotns__SiteStatsDataPoint(struct soap*, const char *, int, tns__SiteStatsDataPoint *const*, const char *);
SOAP_FMAC3 tns__SiteStatsDataPoint ** SOAP_FMAC4 soap_get_PointerTotns__SiteStatsDataPoint(struct soap*, tns__SiteStatsDataPoint **, const char*, const char*);
SOAP_FMAC3 tns__SiteStatsDataPoint ** SOAP_FMAC4 soap_in_PointerTotns__SiteStatsDataPoint(struct soap*, const char*, tns__SiteStatsDataPoint **, const char*);

#ifndef SOAP_TYPE_PointerToArrayOfGroupObject
#define SOAP_TYPE_PointerToArrayOfGroupObject (54)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToArrayOfGroupObject(struct soap*, ArrayOfGroupObject *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToArrayOfGroupObject(struct soap*, ArrayOfGroupObject *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerToArrayOfGroupObject(struct soap*, ArrayOfGroupObject **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToArrayOfGroupObject(struct soap*, ArrayOfGroupObject **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToArrayOfGroupObject(struct soap*, const char *, int, ArrayOfGroupObject *const*, const char *);
SOAP_FMAC3 ArrayOfGroupObject ** SOAP_FMAC4 soap_get_PointerToArrayOfGroupObject(struct soap*, ArrayOfGroupObject **, const char*, const char*);
SOAP_FMAC3 ArrayOfGroupObject ** SOAP_FMAC4 soap_in_PointerToArrayOfGroupObject(struct soap*, const char*, ArrayOfGroupObject **, const char*);

#ifndef SOAP_TYPE_PointerTotns__GroupObject
#define SOAP_TYPE_PointerTotns__GroupObject (55)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotns__GroupObject(struct soap*, tns__GroupObject *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTotns__GroupObject(struct soap*, tns__GroupObject *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTotns__GroupObject(struct soap*, tns__GroupObject **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotns__GroupObject(struct soap*, tns__GroupObject **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotns__GroupObject(struct soap*, const char *, int, tns__GroupObject *const*, const char *);
SOAP_FMAC3 tns__GroupObject ** SOAP_FMAC4 soap_get_PointerTotns__GroupObject(struct soap*, tns__GroupObject **, const char*, const char*);
SOAP_FMAC3 tns__GroupObject ** SOAP_FMAC4 soap_in_PointerTotns__GroupObject(struct soap*, const char*, tns__GroupObject **, const char*);

#ifndef SOAP_TYPE_PointerToArrayOfSiteStatsDataPoint
#define SOAP_TYPE_PointerToArrayOfSiteStatsDataPoint (56)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToArrayOfSiteStatsDataPoint(struct soap*, ArrayOfSiteStatsDataPoint *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToArrayOfSiteStatsDataPoint(struct soap*, ArrayOfSiteStatsDataPoint *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerToArrayOfSiteStatsDataPoint(struct soap*, ArrayOfSiteStatsDataPoint **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToArrayOfSiteStatsDataPoint(struct soap*, ArrayOfSiteStatsDataPoint **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToArrayOfSiteStatsDataPoint(struct soap*, const char *, int, ArrayOfSiteStatsDataPoint *const*, const char *);
SOAP_FMAC3 ArrayOfSiteStatsDataPoint ** SOAP_FMAC4 soap_get_PointerToArrayOfSiteStatsDataPoint(struct soap*, ArrayOfSiteStatsDataPoint **, const char*, const char*);
SOAP_FMAC3 ArrayOfSiteStatsDataPoint ** SOAP_FMAC4 soap_in_PointerToArrayOfSiteStatsDataPoint(struct soap*, const char*, ArrayOfSiteStatsDataPoint **, const char*);

#ifndef SOAP_TYPE_PointerTotns__Bug
#define SOAP_TYPE_PointerTotns__Bug (57)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotns__Bug(struct soap*, tns__Bug *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTotns__Bug(struct soap*, tns__Bug *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTotns__Bug(struct soap*, tns__Bug **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotns__Bug(struct soap*, tns__Bug **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotns__Bug(struct soap*, const char *, int, tns__Bug *const*, const char *);
SOAP_FMAC3 tns__Bug ** SOAP_FMAC4 soap_get_PointerTotns__Bug(struct soap*, tns__Bug **, const char*, const char*);
SOAP_FMAC3 tns__Bug ** SOAP_FMAC4 soap_in_PointerTotns__Bug(struct soap*, const char*, tns__Bug **, const char*);

#ifndef SOAP_TYPE_PointerTotns__ArrayOfstring
#define SOAP_TYPE_PointerTotns__ArrayOfstring (58)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotns__ArrayOfstring(struct soap*, tns__ArrayOfstring *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTotns__ArrayOfstring(struct soap*, tns__ArrayOfstring *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTotns__ArrayOfstring(struct soap*, tns__ArrayOfstring **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotns__ArrayOfstring(struct soap*, tns__ArrayOfstring **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotns__ArrayOfstring(struct soap*, const char *, int, tns__ArrayOfstring *const*, const char *);
SOAP_FMAC3 tns__ArrayOfstring ** SOAP_FMAC4 soap_get_PointerTotns__ArrayOfstring(struct soap*, tns__ArrayOfstring **, const char*, const char*);
SOAP_FMAC3 tns__ArrayOfstring ** SOAP_FMAC4 soap_in_PointerTotns__ArrayOfstring(struct soap*, const char*, tns__ArrayOfstring **, const char*);

#ifndef SOAP_TYPE_xsd__string
#define SOAP_TYPE_xsd__string (59)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__string(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_xsd__string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__string(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsd__integer
#define SOAP_TYPE_xsd__integer (60)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__integer(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__integer(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_xsd__integer(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__integer(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__integer(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__integer(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__integer(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (61)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (62)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

SOAP_END_NAMESPACE(soap)

#endif

/* end of soapH.h */
