/* soapClientLib.cpp
   Generated by gSOAP 2.3 rev 1 from SoapAPI.h
   Copyright (C) 2001-2003 Genivia inc.
   All Rights Reserved.
*/
#define WITH_NOGLOBAL
#define SOAP_FMAC3 static
#include "soapC.cpp"
#include "soapClient.cpp"

/* end of soapClientLib.cpp */
