#! /bin/sh

usage() {
	echo "$0: [-interact] [-help] [-debug] [-confdir confdir] [-input conffile] [-output conffile] [-httpdconf gforgehttpdconf] [-httpdsecrets gforgehttpdsecrets] [-localinc gforgelocalinc] [-example|-fhs] [-clean] [-noapache] [-dovhost] [-home homepath] [-group grouppath] [-listen80|nolisten80]"
}

getval(){
	echo -n $1 \[$2\] ?
	read $1
}

computedefault(){
	echo "Calculating defaults"
	# This is used to make a default working gforge.conf
	DEFAULTsystem_name=MyGForge
	DEFAULTdomain_name=`hostname -f`
	DEFAULTserver_admin=webmaster@$DEFAULTdomain_name
	DEFAULTdb_host=`hostname -i`
	DEFAULTdb_port=5432
	DEFAULTdb_name=gforge
	DEFAULTdb_user=gforge
	DEFAULTdb_password=$(dd if=/dev/urandom count=256 bs=1 2> /dev/null | md5sum | cut -b1-8)
	DEFAULTip_address=`hostname -i`
	DEFAULTscm_host=scm.$DEFAULTdomain_name
	DEFAULTshell_host=shell.$DEFAULTdomain_name
	DEFAULTusers_host=users.$DEFAULTdomain_name
	DEFAULTlists_host=lists.$DEFAULTdomain_name
	# The following three have to be synced when domain_name changes
	# and docs_host is supposed not to be used
	#DEFAULTdocs_host=gfdocs.$DEFAULTdomain_name
	DEFAULTjabber_host=jabber.$DEFAULTdomain_name
	DEFAULTupload_host=upload.$DEFAULTdomain_name
	#
	DEFAULTdownload_host=download.$DEFAULTdomain_name
	# The following is upload host and dir for FRS
	DEFAULTftpuploadhost=upload.$DEFAULTdomain_name
	DEFAULTftpuploaddir=$GFGDIR/var/lib/gforge/chroot/ftproot
	#
	DEFAULTstatsadmin_groupid=2
	DEFAULTnewsadmin_groupid=3
	DEFAULTpeerrating_groupid=4
	DEFAULTtemplate_project=5
	DEFAULTadmin_login=admin
	DEFAULTadmin_password=$(dd if=/dev/urandom count=256 bs=1 2> /dev/null | md5sum | cut -b1-8)
	DEFAULTskill_list="Ada;C;C++;HTML;LISP;Perl;PHP;Python;SQL"
	DEFAULTdefault_trove_cat=18
	DEFAULTldap_host=localhost
	DEFAULTldap_base_dn="dc=`echo $DEFAULTdomain_name | sed 's/\./,dc=/g'`"
	DEFAULTldap_web_add_password=$(dd if=/dev/urandom count=256 bs=1 2> /dev/null | md5sum | cut -b1-8)
	DEFAULTsys_path_to_mailman=$(if test -d /usr/lib/mailman; then echo /usr/lib/mailman; else echo /var/mailman; fi)
	DEFAULTcgidir=$CGIDIR
	DEFAULTcronolog_path=$(findcronolog)
	DEFAULTsys_path_to_jpgraph=/usr/share/jpgraph/
	DEFAULTsys_path_to_scmweb=/usr/lib/gforge/bin/
	DEFAULTgforge_chroot=$CHROOT
	DEFAULTgforge_etc=$ETCDIR
	DEFAULTsys_custom_path=$ETCDIR/custom
	DEFAULTgroupdir=$GROUPPATH
	DEFAULThomedir=$HOMEPATH
	DEFAULTcvsdir=$CVSPATH
	DEFAULTsvndir=$SVNPATH
	# The place where file uploaded with http are stored for download
	DEFAULTuploaddir=$GFGDIR/var/lib/gforge/download/
	DEFAULTsys_urlroot=$SHAREDIR/www/
	DEFAULTsys_jabber_pass=$(dd if=/dev/urandom count=256 bs=1 2> /dev/null | md5sum | cut -b1-8)
	DEFAULTusr_share_gforge=$SHAREDIR
	DEFAULTusr_lib_gforge=$LIBDIR
	DEFAULTvar_lib_gforge=$GFGDIR/var/lib/gforge
	DEFAULTvar_log_gforge=$GFGDIR/var/log/gforge
	DEFAULTsys_show_source=0
	DEFAULTsys_force_login=0
	DEFAULTsys_session_key=$(dd if=/dev/urandom count=256 bs=1 2> /dev/null | md5sum | cut -b1-32)
	DEFAULTsys_session_expire='60 * 60 * 24 * 7'
	DEFAULTsys_show_contact_info=1
	DEFAULTsys_themeroot=$SHAREDIR/www/themes/
	DEFAULTsys_theme=gforge
	DEFAULTsys_lang=English
	DEFAULTsys_default_timezone=GMT
	DEFAULTsys_default_country_code=US
	DEFAULTsys_account_manager_type=$SYSTEM
	DEFAULTsys_use_jabber=0
	DEFAULTsys_use_auth_ldap=1
	# Couldn't find where this is used, maybe some rest of ext auth
	#DEFAULTsys_ldap_auth_host=localhost
	DEFAULTsys_ldap_auth_port=389
	DEFAULTsys_ldap_auth_version=3
	DEFAULTsys_ldap_auth_dn="dc=`echo $DEFAULTdomain_name | sed 's/\./,dc=/g'`"
	DEFAULTsys_scm_tarballs_path=$GFGDIR/var/lib/gforge/scmtarballs
	DEFAULTsys_scm_snapshots_path=$GFGDIR/var/lib/gforge/scmsnapshots
	DEFAULTsys_use_scm=true
	DEFAULTsys_use_tracker=true
	DEFAULTsys_use_forum=true
	DEFAULTsys_use_pm=true
	DEFAULTsys_use_docman=true
	DEFAULTsys_use_news=true
	DEFAULTsys_use_mail=true
	DEFAULTsys_use_survey=true
	DEFAULTsys_use_frs=true
	DEFAULTsys_use_fti=false
	DEFAULTsys_use_ftp=true
	DEFAULTsys_use_trove=true
	DEFAULTsys_use_snippet=true
	DEFAULTsys_use_shell=true
	DEFAULTsys_use_ssl=false
	DEFAULTsys_use_people=true
	DEFAULTsys_use_ftpuploads=false
	DEFAULTsys_use_gateways=true
	DEFAULTsys_use_project_vhost=true
	DEFAULTsys_use_project_database=false
	DEFAULTsys_use_project_multimedia=false
	DEFAULTsys_project_reg_restricted=false
	DEFAULTsys_user_reg_restricted=false
	DEFAULTsys_localization_enable_caching=true
	DEFAULTsys_localization_cache_path=$GFGDIR/var/cache/gforge/
	DEFAULTsys_localization_enable_timestamp_checking=true
	DEFAULTsys_localinc=$ETCDIR/local.inc
	DEFAULTsys_jabber_pass=$(dd if=/dev/urandom count=256 bs=1 2> /dev/null | md5sum | cut -b1-8)
	DEFAULTsys_plugins_path=/usr/lib/gforge/plugins/
	DEFAULTsys_sslcrt=$(findcrt)
	DEFAULTsys_sslkey=$(findkey)
	DEFAULTnoreply_to_bitbucket=true
	DEFAULTsys_simple_dns=true
	DEFAULTsys_apache_user=$(findapacheowner)
	DEFAULTsys_apache_group=$(findapacheowner)
	DEFAULTsys_forum_return_domain=$DEFAULTdomain_name
	# added for massmail error 11/2005 fabio bertagnin transiciel
	DEFAULTsys_sendmail_path=/usr/sbin/sendmail
	#
	# TODO
	#usr_lib_gforge=$GFGDIR
	#vhost_name
	#docdir
}

findcrt(){
	if [ -f /etc/apache2/ssl/apache.pem ]
	then
		echo /etc/apache2/ssl/apache.pem
	else
		if [ -f /etc/apache/ssl.crt/server.crt ]
		then 
		 	echo /etc/apache/ssl.crt/server.crt
		fi
	fi
}
findkey(){
	if [ -f /etc/apache2/ssl/apache.pem ]
	then
		echo /etc/apache2/ssl/apache.pem
	else
		if [ -f /etc/apache/ssl.key/server.key ]
		then 
			echo /etc/apache/ssl.key/server.key
		fi
	fi
}

findcronolog(){
	if [ -x /usr/bin/cronolog ]
	then 
		echo /usr/bin/cronolog
	else
		if [ -x /usr/sbin/cronolog ]
		then
			echo /usr/sbin/cronolog
		else
			which cronolog
		fi
	fi
}
findapacheowner(){
	if grep 'Red Hat' /etc/issue > /dev/null; then
		echo apache
	elif grep SuSE /etc/issue > /dev/null; then
		echo apache
	elif grep Debian /etc/issue > /dev/null; then
		echo www-data
	else
		echo apache
	fi
}

writedefault(){
	# Here is the fun
	# This create a default conf file in $1 
	tmpfile=$1.$$computedefault
	echo "cat >$1<<-EOF" > $tmpfile
	cat $0 | grep "^	DEFAULT" | sed 's/	DEFAULT\(.[^=]*\)=.*/\1=\${\1:-\$DEFAULT\1}/' >> $tmpfile
	echo 'EOF' >> $tmpfile
	. $tmpfile
	rm -f $tmpfile
}

readdefault() {
	cat $1 | sed 's/\(.[^=]*\)=\(.*\)/DEFAULT\1="\2"/' |
		grep -v '^DEFAULTcronolog_path' > $1.$$readdefault
	. $1.$$readdefault

	if [ ! -z "$DEFAULTsys_sslcrt" -a ! -f "$DEFAULTsys_sslcrt" ]
	then
		unset DEFAULTsys_sslcrt
		DEFAULTsys_sslcrt=$(findcrt)
	else
		if [ -z "$DEFAULTsys_sslcrt" ]
		then
			DEFAULTsys_sslcrt=$(findcrt)
		fi
	fi
	if [ ! -z "$DEFAULTsys_sslkey" -a ! -f "$DEFAULTsys_sslkey" ]
	then
		unset DEFAULTsys_sslkey
		DEFAULTsys_sslkey=$(findkey)
	else
		if [ -z "$DEFAULTsys_sslkey" ]
		then
			DEFAULTsys_sslkey=$(findkey)
		fi
	fi
	if [ ! -d "$DEFAULTsys_themeroot/$DEFAULTsys_theme" ]
	then
		if [ -d "$DEFAULTsys_themeroot/gforge" ]
		then
			DEFAULTsys_theme=gforge
		fi
	fi
	rm -f $1.$$readdefault
}

setupinout(){

	computedefault

	writedefault $CONFFILEIN.new

	if [ -f $CONFFILEIN ]
	then
		echo "Reading defaults from $CONFFILEIN"
		readdefault $CONFFILEIN
	else
		readdefault $CONFFILEIN.new
	fi
	
	if [ "$interact" == true ]
	then
		echo "Enter values or type enter for defaults:"
		# Here is the fun II
		# This ask for change of default
		tmpfile=$1.$$getval
		cat $0 | grep "^	DEFAULT" | sed 's/	DEFAULT\(.[^=]*\)=.*/getval \1 "\${DEFAULT\1}"/' > $tmpfile
	else
		cat $0 | grep "^	DEFAULT" | sed 's/	DEFAULT\(.[^=]*\)=.*/\1="\${DEFAULT\1}"/' > $tmpfile
	fi
	. $tmpfile
	rm -f $tmpfile
	
	echo "Creating $CONFFILEOUT"
	[ ! -d `dirname $CONFFILEOUT` ] && (mkdir -p `dirname $CONFFILEOUT` || (echo "Could not create `dirname $CONFFILEOUT`" && exit 1))
	writedefault $CONFFILEOUT.new
	mv $CONFFILEOUT.new $CONFFILEOUT
	
	
	# Remove trailing space
	cat $CONFFILEIN | sed 's/ *$//' > $CONFFILEIN.new
	mv $CONFFILEIN.new $CONFFILEIN
	
	# Fill in the blanks
	EXCLUDEVHOST=' -not -name 55vhost'
	if [ "$dovhost" == true ]
	then
		EXCLUDEVHOST='' 		
	fi
	rm -f $ETCDIR/httpd.d/10cvs
	rm -f $ETCDIR/httpd.d/10scmcvs
	rm -f $ETCDIR/httpd.d/10scmcvsauth
	rm -f $ETCDIR/httpd.d/07maindirhttps
	rm -f $ETCDIR/httpd.d/11scmcvshttp
	rm -f $ETCDIR/httpd.d/11scmsvnhttp
	rm -f $ETCDIR/httpd.d/12scmcvshttp.ssl

	find $ETCDIR/httpd.d  -type f -regex "$ETCDIR/httpd.d/\([a-z0-9]+\|_?([a-z0-9_.]+-)+[a-z0-9]+\|[a-z0-9][a-z0-9-]*\)\(\|.ssl\|.secrets\)" $EXCLUDEVHOST | sort | while read i
	do
		$BINDIR/fill-in-the-blanks.pl $i $ETCDIR/`basename $i`.gforge-new $CONFFILEOUT
	done
	
	if [ $listen80 == false ]
	then
		rm -f $ETCDIR/00listen80.gforge-new
	fi

	echo "Creating $HTTPDCONF"
	ls $ETCDIR/[0-9][0-9]*.gforge-new | sort | xargs cat > $HTTPDCONF
	rm $ETCDIR/[0-9][0-9]*.gforge-new
	echo "Creating $HTTPDSECRETS"
	cat $ETCDIR/httpd.secrets.gforge-new > $HTTPDSECRETS
	rm $ETCDIR/httpd.secrets.gforge-new
	
	echo "Creating $LOCALINC"
	find $ETCDIR/local.d -type f -regex "$ETCDIR/local.d/\([a-z0-9]+\|_?([a-z0-9_.]+-)+[a-z0-9]+\|[a-z0-9][a-z0-9-]*\)\(\|.$database\)" | sort | while read i 
	do
		$BINDIR/fill-in-the-blanks.pl $i $CONFFILEOUTDIR/`basename $i` $CONFFILEOUT
	done
	(find $CONFFILEOUTDIR  -type f -regex "$CONFFILEOUTDIR/\([a-z0-9]+\|_?([a-z0-9_.]+-)+[a-z0-9]+\|[a-z0-9][a-z0-9-]*\)\(\|.$database\)" | sort | xargs cat ) > $LOCALINC
	find $CONFFILEOUTDIR  -type f -regex "$CONFFILEOUTDIR/\([a-z0-9]+\|_?([a-z0-9_.]+-)+[a-z0-9]+\|[a-z0-9][a-z0-9-]*\)\(\|.$database\)" -print0 | xargs -0 rm 

	echo "Creating other includes"
	#for i in $ETCDIR/templates/[a-z]*
	find $ETCDIR/templates -name '[a-z]*' -maxdepth 1 -type f | while read i 
	do
		$BINDIR/fill-in-the-blanks.pl $i $CONFFILEOUTDIR/`basename $i` $CONFFILEOUT
	done
	chmod 600 $HTTPDSECRETS $CONFFILEIN $CONFFILEOUT
	chmod 640 $CONFFILEOUTDIR/local.pl $CONFFILEOUTDIR/database.inc
	chown gforge:gforge $CONFFILEOUTDIR/local.pl $CONFFILEOUTDIR/database.inc
}
	
doapache() {	
	APACHECONF=/etc/apache/httpd.conf
	GFORGE_ETC_SEARCH=$HTTPDCONF
	export GFORGE_ETC_SEARCH
	if [ -f $APACHECONF -a -f $BINDIR/install-apache.sh ] ; then
		if [ ! -f /etc/apache/conf.d/gforge.httpd.conf ] ; then
			if ! grep -q "^Include $GFORGE_ETC_SEARCH" $APACHECONF ; then
				$BINDIR/install-apache.sh setup
			else 
				echo "Found Include $GFORGE_ETC_SEARCH in $APACHECONF"
			fi
		else
			LINK=`ls -l /etc/apache/conf.d/gforge.httpd.conf | sed 's/.*-> \(.*\)$/\1/'`
			if [ "$LINK" != "$GFORGE_ETC_SEARCH" ] ; then
				echo Need to readjust Symlink
				$BINDIR/install-apache.sh setup
			fi
			if ! grep -q "^Include $GFORGE_ETC_SEARCH" $APACHECONF ; then
				echo "Found /etc/apache/conf.d/gforge.httpd.conf"
			else 
				# There is a link and an include
				$BINDIR/install-apache.sh setup
			fi
		fi
	fi
}


cleanplugindirs() {
	for dir in www/plugins cronjobs/plugins db/plugins plugins/bin plugins/cgi-bin plugins etc/plugins 
	do 
		[ -d $dir ] && rmdir $dir && echo "# $dir removed" 
	done
}

setupplugindirs() {
	for dir in www/plugins cronjobs/plugins db/plugins plugins plugins/bin plugins/cgi-bin etc/plugins 
	do 
		[ ! -d $dir ] && mkdir $dir && echo "# Creating $dir" || echo "# $dir already exists" 
	done
}

setupplugin() {
	if [ -d "$1" ]
	then
		PLUGINDIR=$1
		CURDIR=`pwd`
		cd $PLUGINDIR
		PLUGINDIR=`pwd`
		cd $CURDIR

		PLUGINNAME=`basename $1 | sed 's/gforge-plugin-//' `
		echo "# Setting symlinks for $PLUGINNAME plugin"
		# www stuffs
		echo "# www stuffs"
		if [ -d "$PLUGINDIR/www" -a -d "www/plugins" ] 
		then 
			echo "ln -s $PLUGINDIR/www www/plugins/$PLUGINNAME" 
			ln -s $PLUGINDIR/www www/plugins/$PLUGINNAME 
		fi 
		# cronjobs stuffs
		echo "# cronjobs stuffs"
		if [ -d "$PLUGINDIR/cronjobs" -a -d "cronjobs/plugins" ] 
		then 
			echo "ln -s $PLUGINDIR/cronjobs cronjobs/plugins/$PLUGINNAME" 
			ln -s $PLUGINDIR/cronjobs cronjobs/plugins/$PLUGINNAME
		fi 
		# lib stuffs
		echo "# lib stuffs"
		if [ -d "$PLUGINDIR/lib" -a -d "db/plugins" ] 
		then 
			echo "ln -s $PLUGINDIR/lib db/plugins/$PLUGINNAME" 
			ln -s $PLUGINDIR/lib db/plugins/$PLUGINNAME
		fi 
		# include stuffs
		echo "# include stuffs"
		if [ -d "$PLUGINDIR/include" -a -d "plugins" ] 
		then 
			echo "ln -s $PLUGINDIR/include plugins/$PLUGINNAME" 
			ln -s $PLUGINDIR/include plugins/$PLUGINNAME 
		fi 
		# cgi-bin stuffs
		echo "# cgi-bin stuffs"
		if [ -d "$PLUGINDIR/cgi-bin" -a -d "cgi-bin" ] 
		then 
			echo "ln -s $PLUGINDIR/cgi-bin cgi-bin/$PLUGINNAME" 
			ln -s $PLUGINDIR/cgi-bin cgi-bin/$PLUGINNAME
		fi 
		# bin stuffs
		echo "# bin stuffs"
		if [ -d "$PLUGINDIR/bin" -a -d "plugins/bin" ] 
		then 
			echo "ln -s $PLUGINDIR/bin plugins/bin/$PLUGINNAME" 
			ln -s $PLUGINDIR/bin plugins/bin/$PLUGINNAME
		fi 
		# etc/plugins stuffs
		echo "# etc/plugins stuffs"
		if [ -d "$PLUGINDIR/etc/plugins/$PLUGINNAME" -a -d "etc/plugins" ] 
		then 
			echo "ln -s $PLUGINDIR/etc/plugins/$PLUGINNAME etc/plugins/$PLUGINNAME" 
			ln -s $PLUGINDIR/etc/plugins/$PLUGINNAME etc/plugins/$PLUGINNAME
		fi 
		# etc/httpd.d stuffs
		echo "# etc/httpd.d stuffs"
		if [ -d "$PLUGINDIR/etc/httpd.d" -a -d "etc/httpd.d" ] 
		then 
			for file in $PLUGINDIR/etc/httpd.d/[0-9][0-9]*
			do
				BASEN=`basename $file`
				echo "ln -s $file etc/httpd.d/$BASEN" 
				ln -s $file etc/httpd.d/$BASEN 
			done
		fi 
		exit 0
	else
		echo "Couldn't find $1 directory"
		exit 1
	fi
}

delplugin() {
	if [ -d "$1" ]
	then
		PLUGINDIR=$1
		PLUGINNAME=`basename $1 | sed 's/gforge-plugin-//' `
		echo "# Setting symlinks for $PLUGINNAME plugin"
		# www stuffs
		echo "# www stuffs"
		if [ -d "$PLUGINDIR/www" -a -d "www/plugins" ] 
		then 
			echo "rm www/plugins/$PLUGINNAME" 
			rm www/plugins/$PLUGINNAME 
		fi 
		# cronjobs stuffs
		echo "# cronjobs stuffs"
		if [ -d "$PLUGINDIR/cronjobs" -a -d "cronjobs/plugins" ] 
		then 
			echo "rm cronjobs/plugins/$PLUGINNAME" 
			rm cronjobs/plugins/$PLUGINNAME
		fi 
		# lib stuffs
		echo "# lib stuffs"
		if [ -d "$PLUGINDIR/lib" -a -d "db/plugins" ] 
		then 
			echo "rm db/plugins/$PLUGINNAME" 
			rm db/plugins/$PLUGINNAME
		fi 
		# include stuffs
		echo "# include stuffs"
		if [ -d "$PLUGINDIR/include" -a -d "plugins" ] 
		then 
			echo "rm plugins/$PLUGINNAME" 
			rm plugins/$PLUGINNAME 
		fi 
		# cgi-bin stuffs
		echo "# cgi-bin stuffs"
		if [ -d "$PLUGINDIR/cgi-bin" -a -d "cgi-bin" ] 
		then 
			echo "rm cgi-bin/$PLUGINNAME" 
			rm cgi-bin/$PLUGINNAME
		fi 
		# bin stuffs
		echo "# bin stuffs"
		if [ -d "$PLUGINDIR/bin" -a -d "plugins/bin" ] 
		then 
			echo "rm plugins/bin/$PLUGINNAME" 
			rm plugins/bin/$PLUGINNAME
		fi 
		# etc/plugins stuffs
		echo "# etc/plugins stuffs"
		if [ -d "$PLUGINDIR/etc/plugins/$PLUGINNAME" -a -d "etc/plugins" ] 
		then 
			echo "rm etc/plugins/$PLUGINNAME" 
			rm etc/plugins/$PLUGINNAME
		fi 
		# etc/httpd.d stuffs
		echo "# etc/httpd.d stuffs"
		if [ -d "$PLUGINDIR/etc/httpd.d" -a -d "etc/httpd.d" ] 
		then 
			for file in $PLUGINDIR/etc/httpd.d/[0-9][0-9]*
			do
				BASEN=`basename $file`
				echo "rm etc/httpd.d/$BASEN" 
				rm etc/httpd.d/$BASEN 
			done
		fi 
		exit 0
	else
		echo "Couldn't find $1 directory"
		exit 1
	fi
}

ETCDIR=`pwd`/etc
BINDIR=`pwd`/utils
CGIDIR=`pwd`/cgi-bin
GFGDIR=`pwd`
CHROOT=''
HOMEPATH=/home
GROUPPATH=/home/groups
CVSPATH=/cvsroot
SVNPATH=/svnroot
SHAREDIR=`pwd`
LIBDIR=`pwd`
CONFFILEOUTDIR=$ETCDIR
CONFFILEIN=$ETCDIR/gforge.conf
CONFFILEOUT=$ETCDIR/gforge.conf
LOCALINC=$ETCDIR/local.inc
HTTPDCONF=$ETCDIR/httpd.conf
HTTPDSECRETS=$ETCDIR/httpd.secrets
SYSTEM=pgsql
export ETCDIR BINDIR GFGDIR CONFFILEOUTDIR CONFFILEIN CONFFILEOUT LOCALINC HTTPDCONF HTTPDSECRETS DOAPACHE SYSTEM
interact=false
noapache=false
database=env
dovhost=false
listen80=true

while [ $# -ne 0 ]
do
	case "$1" in
		-interact )
			interact=true
			;;
		-help )
			usage
			exit 0
			;;
		-httpdsecrets )
			shift
			HTTPDSECRETS=$1
			;;
		-httpdconf )
			shift
			HTTPDCONF=$1
			;;
		-localinc )
			shift
			LOCALINC=$1
			;;
		-input )
			shift
			CONFFILEIN=$1
			;;
		-output )
			shift
			CONFFILEOUT=$1
			;;
		-system )
			shift
			SYSTEM=$1
			;;
		-confdir )
			shift
			CONFFILEOUTDIR=$1
			CONFFILEIN=$1/gforge.conf
			CONFFILEOUT=$1/gforge.conf
			LOCALINC=$1/local.inc
			HTTPDCONF=$1/httpd.conf
			HTTPDSECRETS=$1/httpd.secrets
			echo Using $1 as config directory
			;;
		-fhs )
			shift
			ETCDIR=/etc/gforge
			BINDIR=/usr/lib/gforge/bin
			CGIDIR=/usr/lib/gforge/cgi-bin
			GFGDIR=''
			HOMEPATH=/home/users
			GROUPPATH=/home/groups
			CHROOT=/var/lib/gforge/chroot
			SHAREDIR=/usr/share/gforge
			LIBDIR=/usr/lib/gforge
			CONFFILEOUTDIR=/etc/gforge
			CONFFILEIN=/etc/gforge/gforge.conf
			CONFFILEOUT=/etc/gforge/gforge.conf
			LOCALINC=/etc/gforge/local.inc
			HTTPDCONF=/etc/gforge/httpd.conf
			HTTPDSECRETS=/etc/gforge/httpd.secrets
			;;
		-simple )
			database=simple
			;;
		-noapache )
			noapache=true
			;;
		-dovhost )
			dovhost=true
			;;
		-listen80 )
			listen80=true
			;;
		-nolisten80 )
			listen80=false
			;;
		-example )
			shift
			CONFFILEIN=$ETCDIR/gforge.conf.example
			CONFFILEOUT=$ETCDIR/gforge.conf.example
			LOCALINC=$ETCDIR/local.inc.example
			HTTPDCONF=$ETCDIR/httpd.conf.example
			HTTPDSECRETS=$ETCDIR/httpd.secrets.example
			database=simple
			noapache=true
			;;
		-home )
			shift
			HOMEPATH=$1
			;;
		-group )
			shift
			GROUPPATH=$1
			;;
		-clean )
			[ -f $CONFFILEIN ] && echo Removing $CONFFILEIN && rm -f $CONFFILEIN
			[ -f $CONFFILEOUT ] && echo Removing $CONFFILEOUT && rm -f $CONFFILEOUT
			[ -f $LOCALINC ] && echo Removing $LOCALINC && rm -f $LOCALINC
			[ -f $HTTPDCONF ] && echo Removing $HTTPDCONF && rm -f $HTTPDCONF
			[ -f $HTTPDSECRETS ] && echo Removing $HTTPDSECRETS && rm -f $HTTPDSECRETS
			exit 0
			;;
		-debug )
			set -x
			;;
		-cleanplugindir)
			cleanplugindirs
			exit 0
			;;
		-plugindir)
			setupplugindirs
			exit 0
			;;
		-plugin)
			shift
			PLUGINPATH=$1
			setupplugin $PLUGINPATH
			;;
		-delplugin)
			shift
			PLUGINPATH=$1
			delplugin $PLUGINPATH
			;;
		*)
			echo "Bad Parameter"
			usage
			exit 1
			;;
	esac
	shift
done
setupinout
[ "$noapache" != true ] && doapache
