DROP FUNCTION plugin_wiki_prepare_rename_page(integer, integer);
DROP FUNCTION plugin_wiki_update_recent(integer, integer);
DROP VIEW plugin_wiki_existing_page;
DROP VIEW plugin_wiki_curr_page;
DROP TABLE plugin_wiki_link;
DROP TABLE plugin_wiki_member;
DROP TABLE plugin_wiki_nonempty;
DROP TABLE plugin_wiki_pagedata;
DROP TABLE plugin_wiki_pageperm;
DROP TABLE plugin_wiki_pref;
DROP TABLE plugin_wiki_rating;
DROP TABLE plugin_wiki_recent;
DROP TABLE plugin_wiki_session;
DROP TABLE plugin_wiki_versiondata;
DROP TABLE plugin_wiki_version;
DROP TABLE plugin_wiki_page;
DROP TABLE plugin_wiki_accesslog;
