# $Id: Makefile 7351 2010-04-27 01:44:31Z vargenau $
#
# themes/Crao/Makefile
#
# minify CSS and JS
#

CSS_SRC = crao.css
CSS_FILES = $(patsubst %.css,%-min.css,$(CSS_SRC))
MAIN    = sticky
JS_MAIN = sticky.js

all	: css js

include ../Makefile.global
