#! /bin/sh
debmirror /var/lib/gforge/chroot/home/groups/fusionforge/htdocs/debian --method=http --host=debian.fusionforge.org -r debian -d lenny,etch,sid -a i386 -s main -v --progress
debmirror /var/lib/gforge/chroot/home/groups/fusionforge/htdocs/ubuntu --method=http --host=debian.fusionforge.org -r ubuntu -d hardy,gutsy,intrepid -a i386 -s main -v --progress
