# $Id: Makefile 7431 2010-05-21 08:29:37Z vargenau $
#
# themes/MacOSX/Makefile
#
# minify CSS and JS
#
# TODO: resolve @import

CSS_SRC = MacOSX.css MacOSX-topbottombars.css
#MAIN    = MacOSX
#JS_MAIN = MacOSX.js
JS_REST = 

CSS_FILES = $(patsubst %.css,%-min.css,$(CSS_SRC))

all	: css

include ../Makefile.global


