ALTER TABLE USERS ADD COLUMN address TEXT;
ALTER TABLE USERS ADD COLUMN phone TEXT;
ALTER TABLE USERS ADD COLUMN fax TEXT;
ALTER TABLE USERS ADD COLUMN title TEXT;
ALTER TABLE frs_dlstats_file ADD COLUMN user_id int;

