include ../../GNUmakefile.defaults

all:
	@echo "No default action"

install:
	install -d -m 755 $(DESTDIR)$(data_path)/plugins/mediawiki/dumps
	install -d -m 755 $(DESTDIR)$(data_path)/plugins/mediawiki/projects
