<?php

/**
 * GForge ViewCVS PHP wrapper.
 *
 * Portion of this file is inspired from the ViewCVS wrapper
 * contained in CodeX.
 * Copyright (c) Xerox Corporation, CodeX / CodeX Team, 2001,2002. All Rights Reserved.
 * http://codex.xerox.com
 *
 * @version   $ID$
 */

// make sure we're not compressing output if we are making a tarball
if (getStringFromRequest('view') == 'tar') {
	$no_gz_buffer=true;
}

require_once('pre.php');
require_once('www/scm/include/scm_utils.php');
require_once('www/plugins/scmsvn/viewcvs_utils.php');

if (!$sys_use_scm) {
	exit_disabled();
}

// Get the project name from query
if(getStringFromGet('root') && strpos(getStringFromGet('root'), ';') === false) {
	$projectName = getStringFromGet('root');
} else {
	$queryString = getStringFromServer('QUERY_STRING');
	if(preg_match_all('/[;]?([^\?;=]+)=([^;]+)/', $queryString, $matches, PREG_SET_ORDER)) {
		for($i = 0, $size = sizeof($matches); $i < $size; $i++) {
			$query[$matches[$i][1]] = urldecode($matches[$i][2]);
		}
		$projectName = $query['root'];
	}
}
// Remove eventual leading /root/ or root/
$projectName = ereg_replace('^..[^/]*/','', $projectName);
if (!$projectName) {
	exit_no_group();
}

// Check permissions
$Group =& group_get_object_by_name($projectName);
if (!$Group || !is_object($Group)) {
	exit_error($Language->getText('general','error'),
		$Language->getText('general','error_creating_group'));
} else if ($Group->isError()) {
	exit_error($Language->getText('general','error'),
		$Group->getErrorMessage());
}
if (!$Group->usesSCM()) {
	exit_error($Language->getText('general','error'),
		$Language->getText('scm_index','error_this_project_has_turned_off'));
}
$perm = & $Group->getPermission(session_get_user());
if ((!$Group->enableAnonSCM() && !($perm && is_object($perm) && $perm->isMember()))
	|| !isset($GLOBALS['sys_path_to_scmweb'])
	|| !is_file($GLOBALS['sys_path_to_scmweb'].'/viewcvs.cgi')) {
	exit_permission_denied();
}

// Call to ViewCVS CGI
$content = viewcvs_execute();

// Set content type header from the value set by ViewCVS
// No other headers are generated by ViewCVS because in generate_etags
// is set to 0 in the ViewCVS config file
$found = false;
$line = strtok($content,SEPARATOR);
while ($line && !$found) {
	if (preg_match('/^Content-Type:(.*)$/',$line,$matches)) {
		header('Content-Type:' . $matches[1]);
 		$found = true;
 	}
	$line = strtok(SEPARATOR);	
}
$content = substr($content, strpos($content,$line));

if (viewcvs_is_html()) {
	// If we output html and we found the mbstring extension, we
	// should try to encode the output of ViewCVS in UTF-8
	if (extension_loaded('mbstring')) {
		$encoding = mb_detect_encoding($content);
		if($encoding != 'UTF-8') {
			$content = mb_convert_encoding($content, 'UTF-8', $encoding);
		}
	}
	scm_header(array('title'=>$Language->getText('scm_index','svn_repository'),
		'group'=>$Group->getID()));
	echo $content;
	scm_footer(array());
} else {
	// TODO does not seem to work when allow_tar = 1 in ViewCVS conf
	// (allow to generate on the fly a tar.gz): the generated file
	// seems to be corrupted
	echo $content;
}

?>
