#! /bin/sh
get_config() {
    echo "Read config from tests/config/default"
    . $(dirname $0)/config/default
    if [ -f $(dirname $0)/config/$(hostname) ]; then
	echo "Read config from tests/config/$(hostname)"
	. $(dirname $0)/config/$(hostname)
    fi
    if [ ! -z "$1" ]
    then
	echo "Set HOST to $1"
        export HOST="$1"
    fi
}

prepare_workspace() {
    export CURDIR=`pwd`
    WORKDIR=$(cd $CURDIR/..; pwd)
    export WORKSPACE=${WORKSPACE:-$WORKDIR}
    export RPM_TMP=$WORKDIR/tmp
    export BUILDRESULT=$WORKSPACE/build/packages
    mkdir -p $BUILDRESULT
    export BUILDERDIR=${BUILDERDIR:-$HOME/builder}
    # Create place to store built packages
    [ ! -d $WORKSPACE/packages ] || mkdir -p $WORKSPACE/packages
    # Erase reports
    [ ! -d $WORKSPACE/reports ] || rm -fr $WORKSPACE/reports
    mkdir -p $WORKSPACE/reports/coverage
    # Erase apidocs
    [ ! -d $WORKSPACE/apidocs ] || rm -fr $WORKSPACE/apidocs
    mkdir -p $WORKSPACE/apidocs
}
