<?php
//
// SourceForge: Breaking Down the Barriers to Open Source Development
// Copyright 1999-2000 (c) The SourceForge Crew
// http://sourceforge.net
//

require_once '../env.inc.php';
require_once $gfwww.'include/pre.php';

function get_rss_20_doc () {
	return '&nbsp;(<a href="http://blogs.law.harvard.edu/tech/rss">RSS 2.0</a>)&nbsp;' . 
		html_image('ic/rss.png',16,16,array('border'=>'0'));
}

function get_rss_feed_20 ($page,$rss_title) {
	// RSS 2.0 format
	$rss_feed_20 .= '<li><a href="' . $page . '">' . $rss_title . '</a>';
	$rss_feed_20 .= '<link href="' . $page . '" title="' . $rss_title . ', RSS 2.0" rel="alternate" type="application/rss+xml" />';
	$rss_feed_20 .= get_rss_20_doc () . '</li>';
	return $rss_feed_20;
}

$project = &group_get_object(getIntFromRequest('group_id'));

$HTML->header(array('title'=>_("Project Exports")));

echo '<h2>' . _('RSS/XML Exports') . '</h2><p>';
 
echo sprintf(_('%1$s data is exported in a variety of standard formats. Many of
the export URLs can also accept form/get data to customize the output. All
data generated by these pages is realtime.'),$GLOBALS['sys_name']);

//echo '</p><h3>' . _('News Data') . '</h3><p>';

echo _('To get Project News or New Project Releases of a specific project use the Links below.'); 


$string_rss_091 =  '<ul>';
$string_rss_20 = '<ul>';

// RSS for project news
if ($project->usesNews() && $GLOBALS['sys_use_news']) {
	// RSS 0.91 format
	$string_rss_091 .= '<li><a href="rss_sfnews.php?group_id=' . getIntFromRequest('group_id') . '">' . 
		$GLOBALS['sys_name'] . ' Developer Project News</a>';
	$string_rss_091 .= '<link href="rss_sfnews.php?group_id=' . getIntFromRequest('group_id') . '" title="' . 
		$GLOBALS[sys_name] . ' Developer Project News, RSS 0.91" rel="alternate" type="application/rss+xml" />';
	/* these links are obsolete
	$string_rss_091 .= '(<a href="http://my.netscape.com/publish/formats/rss-spec-0.91.html">RSS 0.91</a>,
		<a href="http://my.netscape.com/publish/formats/rss-0.91.dtd">&lt;rss-0.91.dtd&gt;</a>)&nbsp;' . 
		html_image('ic/rss.png',16,16,array('border'=>'0')) . '</li>';
	*/
	$string_rss_091 .= '&nbsp;(RSS 0.91)';
		
	// RSS 2.0 format
	$string_rss_20 .= get_rss_feed_20 ("rss20_news.php?group_id=" . getIntFromRequest('group_id'),
										$GLOBALS['sys_name'] . _(" Developer Project News"));
}


// RSS for project Activity
if ( ($project->usesNews() && $GLOBALS['sys_use_news']) || 
	($project->usesFRS() && $GLOBALS['sys_use_frs']) || 
	($project->usesTracker() && $GLOBALS['sys_use_tracker']) || 
	($project->usesForum() && $GLOBALS['sys_use_forum']) ||
	($project->usesSCM() && $GLOBALS['sys_use_scm']) ){
	// RSS 2.0 format
	$string_rss_20 .= get_rss_feed_20 ("rss20_activity.php?group_id=" . getIntFromRequest('group_id'),
										$GLOBALS['sys_name'] . _(" Activity"));
}


// RSS for project Releases
if ($project->usesFRS() && $GLOBALS['sys_use_frs']) {
	// RSS 0.91 format
	$string_rss_091 .= '<li><a href="rss_sfnewreleases.php?group_id=' . getIntFromRequest('group_id') . '">' . 
		$GLOBALS['sys_name'] . ' Developer New Project Releases</a>';
	$string_rss_091 .= '<link href="rss_sfnewreleases.php?group_id=' . getIntFromRequest('group_id') . 
		'" title="' . $GLOBALS[sys_name] . ' Developer New Project Releases, RSS 0.91" rel="alternate" type="application/rss+xml" />';
	/* these links are obsolete
	$string_rss_091 .= '(<a href="http://my.netscape.com/publish/formats/rss-spec-0.91.html">RSS 0.91</a>,
		<a href="http://my.netscape.com/publish/formats/rss-0.91.dtd">&lt;rss-0.91.dtd&gt;</a>)&nbsp;' . 
		html_image('ic/rss.png',16,16,array('border'=>'0')) . '</li>';
	*/
	$string_rss_091 .= '&nbsp;(RSS 0.91)';
	
	// RSS 2.0 format
	$string_rss_20 .= get_rss_feed_20 ("rss20_newreleases.php?group_id=" . getIntFromRequest('group_id'),
										$GLOBALS['sys_name'] . _(" Developer New Project Releases"));
}

/* Pages do not exists

// RSS for project Bug Tracker
if ($project->usesTracker() && $GLOBALS['sys_use_tracker']) {
	// RSS 2.0 format
	$string_rss_20 .= get_rss_feed_20 ("rss20_tracker.php?group_id=" . getIntFromRequest('group_id'),
										$GLOBALS['sys_name'] . _(" Developer Bug Tracker"));
}


// RSS for project Documents
if ($project->usesDocman() && $GLOBALS['sys_use_docman']) {
	// RSS 2.0 format
	$string_rss_20 .= get_rss_feed_20 ("rss20_docman.php?group_id=" . getIntFromRequest('group_id'),
										$GLOBALS['sys_name'] . _(" Developer Documents"));
}

// RSS for project Forums Threads
if ($project->usesForum() && $GLOBALS['sys_use_forum']) {
	// RSS 2.0 format
	$string_rss_20 .= get_rss_feed_20 ("rss20_forum.php?group_ids=" . getIntFromRequest('group_id'),
										$GLOBALS['sys_name'] . _(" Developer forum Threads"));
}

*/

$string_rss_091 .= '</ul>';
$string_rss_20 .= '</ul>';

echo $string_rss_091;
echo $string_rss_20;
?>

</p>
<ul>
<li><a href="http://wiki.evolvis.org/evolvis/index.php/RSS">Get more Feeds here.</a></li>
</ul>

<a href="javascript:history.go(-1)">[<?php echo _('Go back') ?>]</a>
<br />
<?php $HTML->footer(array()); ?>
