#! /bin/sh
get_config()
{
	echo "Read config from tests/config/default"
	. tests/config/default
	if [ -f tests/config/`hostname` ]
	then
		echo "Read config from tests/config/`hostname`"
		 . tests/config/`hostname` 
	fi
	if [ ! -z "$1" ]
	then
		echo "Set HOST to $1"
        	export HOST="$1"
	fi
}

prepare_workspace()
{
	export CURDIR=`pwd`
	WORKDIR=$(cd $CURDIR/..; pwd)
	export WORKSPACE=${WORKSPACE:-$WORKDIR}
	export RPM_TMP=$WORKDIR/tmp
	export BUILDRESULT=$WORKSPACE/build/packages
	export BUILDERDIR=${BUILDERDIR:-$HOME/builder}
	# Delete existing packages
	if [ -d $WORKSPACE/build/packages ] 
	then 
		rm -fr $WORKSPACE/build/packages/*
	fi
	# Create place to build package if necessary
	[ ! -d $WORKSPACE/build/packages ] || mkdir -p $WORKSPACE/build/packages
	# Erase config
	[ ! -d $WORKSPACE/build/config ] || rm -fr $WORKSPACE/build/config
	mkdir -p $WORKSPACE/build/config
	# Erase reports
	[ ! -d $WORKSPACE/reports ] || rm -fr $WORKSPACE/reports
	mkdir -p $WORKSPACE/reports/coverage
	# Erase apidocs
	[ ! -d $WORKSPACE/apidocs ] || rm -fr $WORKSPACE/apidocs
	mkdir -p $WORKSPACE/apidocs
}

setup_dag_repo()
{
HOST=$1
# DAG REPO
if [ ! -z "$DAG_RPMFORGE_REPO" ] ; then
        echo "Installing specific DAG REPO $DAG_RPMFORGE_REPO"
        cp src/rpm-specific/dag-rpmforge.repo $WORKSPACE/build/packages/dag-rpmforge.repo
        sed -i "s#http://apt.sw.be/redhat#${DAG_RPMFORGE_REPO}#" $WORKSPACE/build/packages/dag-rpmforge.repo
        scp $WORKSPACE/build/packages/dag-rpmforge.repo root@$HOST:/etc/yum.repos.d/
else
        echo "Installing standard DAG REPO from src/rpm-specific/dag-rpmforge.repo"
        scp src/rpm-specific/dag-rpmforge.repo root@$HOST:/etc/yum.repos.d/
fi
}

setup_ff_repo()
{
HOST=$1
# FUSIONFORGE REPO
if [ ! -z "$FFORGE_RPM_REPO" ]
then
        echo "Installing specific FUSIONFORGE REPO $FFORGE_RPM_REPO"
        cp src/rpm-specific/fusionforge.repo $WORKSPACE/build/packages/fusionforge.repo
        sed -i "s#http://fusionforge.org/#${HUDSON_URL}#" $WORKSPACE/build/packages/fusionforge.repo
        sed -i "s#baseurl = .*#baseurl = ${FFORGE_RPM_REPO}/#" $WORKSPACE/build/packages/fusionforge.repo
        scp $WORKSPACE/build/packages/fusionforge.repo root@$HOST:/etc/yum.repos.d/
else
        rsync -a --delete $BUILDRESULT/ root@$HOST:/root/fusionforge_repo/
        echo "Installing standard FUSIONFORGE REPO from src/rpm-specific/fusionforge.repo"
        scp src/rpm-specific/fusionforge.repo root@$HOST:/etc/yum.repos.d/
fi
}

setup_debian_3rdparty_repo()
{
if [ -z "$HOST" ] ; then  echo "HOST undefined" ;exit 1; fi
if [ -z "$DEB3RD" ] ; then  echo "DEB3RD undefined" ; exit 2 ; fi
if [ -z "$DIST" ] ; then  echo "DIST undefined" ; exit 3 ; fi
echo "Installing debian 3rd party repo $DEB3RD $DIST on $HOST"
ssh root@$HOST "echo \"deb $DEB3RD $DIST main\" > /etc/apt/sources.list.d/3rd-party.list"
wget -q -O - ${DEB3RD}key | ssh root@$HOST "apt-key add -"
}
