#! /bin/sh 

scriptdirname=`dirname $0`
scriptdirparent=`cd $scriptdirname/..;pwd`
scriptdir=$scriptdirparent/scripts
configdir=$scriptdirparent/config
. $scriptdirparent/scripts/common-vm

read_param_vm $@

# Start script for this engine must exist
if [ ! -x $scriptdirparent/${VMENGINE}/start ]
then 
	echo "Don't know how to run ${VMENGINE} engine"
	echo "$scriptdirparent/${VMENGINE}/start not found"
	exit 4
else
	$scriptdirparent/${VMENGINE}/start
fi

# Loop until engine is up and ssh is running
ssh -o 'StrictHostKeyChecking=no' "root@$HOST" uname -a
ret=$?
for loop in 1 2 3 4 5 6 7 8 9
do

	if [ $ret -ne 0 ];then
		echo -n $loop
		sleep 20;
		ssh -o 'StrictHostKeyChecking=no' "root@$HOST" uname -a
		ret=$?
	fi
done
sleep 1
exit $ret
