#! /bin/sh -e

scriptdirname=`dirname $0`
scriptdirparent=`cd $scriptdirname/..;pwd`
scriptdir=$scriptdirparent/scripts
configdir=$scriptdirparent/config
. $scriptdirparent/scripts/common-vm

read_param_vm "$@"

# Start script for this engine must exist
if [ ! -x $scriptdirparent/${VMENGINE}/stop ]
then 
	echo "Don't know how to stop ${VMENGINE} engine"
	echo "$scriptdirparent/${VMENGINE}/stop not found"
	exit 4
else
	$scriptdirparent/${VMENGINE}/stop
fi
